# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/STEUER_MISC.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/SP_FPU.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/REGISTERS.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/I_PFAD.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/ICACHE_SM.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/DP_FPU.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/DECODER.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/ALIGNER.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/ADDR_UNIT.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_median/Sources/hdl/node.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/mips_16_defs.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/instruction_mem.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/data_mem.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/alu.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/CACHE_LOGIK.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/TOP_MISC.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/STEUERUNG.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/ICACHE.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/DCACHE.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/DATENPFAD.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/WB_stage.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_median/Sources/hdl/state_machine.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/register_file.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_median/Sources/hdl/pixel_network.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/MEM_stage.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/IF_stage.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/ID_stage.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/hazard_detection_unit.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/EX_stage.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_median/Sources/hdl/dff_3_pipe.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_median/Sources/hdl/common_network.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_m32632/Sources/hdl/m32632.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_mips_16/Sources/hdl/mips_16.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_median/Sources/hdl/median.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/imports/vivado_workspace/ooc_md5_pipelined/Sources/hdl/md5_pipelined.v
  /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/constrs_1/imports/constrs_1/imports/new/constr.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/mips_16_base/mips_16_base.srcs/constrs_1/imports/constrs_1/imports/new/constr.xdc]


synth_design -top top -part xc7a100tcsg324-3 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
