add ignored outputs ahbo[hconfig][1][0] -both
add ignored outputs ahbo[hconfig][1][10] -both
add ignored outputs ahbo[hconfig][1][11] -both
add ignored outputs ahbo[hconfig][1][12] -both
add ignored outputs ahbo[hconfig][1][13] -both
add ignored outputs ahbo[hconfig][1][14] -both
add ignored outputs ahbo[hconfig][1][15] -both
add ignored outputs ahbo[hconfig][1][16] -both
add ignored outputs ahbo[hconfig][1][17] -both
add ignored outputs ahbo[hconfig][1][18] -both
add ignored outputs ahbo[hconfig][1][19] -both
add ignored outputs ahbo[hconfig][1][1] -both
add ignored outputs ahbo[hconfig][1][20] -both
add ignored outputs ahbo[hconfig][1][21] -both
add ignored outputs ahbo[hconfig][1][22] -both
add ignored outputs ahbo[hconfig][1][23] -both
add ignored outputs ahbo[hconfig][1][24] -both
add ignored outputs ahbo[hconfig][1][25] -both
add ignored outputs ahbo[hconfig][1][26] -both
add ignored outputs ahbo[hconfig][1][27] -both
add ignored outputs ahbo[hconfig][1][28] -both
add ignored outputs ahbo[hconfig][1][29] -both
add ignored outputs ahbo[hconfig][1][2] -both
add ignored outputs ahbo[hconfig][1][30] -both
add ignored outputs ahbo[hconfig][1][31] -both
add ignored outputs ahbo[hconfig][1][3] -both
add ignored outputs ahbo[hconfig][1][4] -both
add ignored outputs ahbo[hconfig][1][5] -both
add ignored outputs ahbo[hconfig][1][6] -both
add ignored outputs ahbo[hconfig][1][7] -both
add ignored outputs ahbo[hconfig][1][8] -both
add ignored outputs ahbo[hconfig][1][9] -both
add ignored outputs ahbo[hconfig][2][0] -both
add ignored outputs ahbo[hconfig][2][10] -both
add ignored outputs ahbo[hconfig][2][11] -both
add ignored outputs ahbo[hconfig][2][12] -both
add ignored outputs ahbo[hconfig][2][13] -both
add ignored outputs ahbo[hconfig][2][14] -both
add ignored outputs ahbo[hconfig][2][15] -both
add ignored outputs ahbo[hconfig][2][16] -both
add ignored outputs ahbo[hconfig][2][17] -both
add ignored outputs ahbo[hconfig][2][18] -both
add ignored outputs ahbo[hconfig][2][19] -both
add ignored outputs ahbo[hconfig][2][1] -both
add ignored outputs ahbo[hconfig][2][20] -both
add ignored outputs ahbo[hconfig][2][21] -both
add ignored outputs ahbo[hconfig][2][22] -both
add ignored outputs ahbo[hconfig][2][23] -both
add ignored outputs ahbo[hconfig][2][24] -both
add ignored outputs ahbo[hconfig][2][25] -both
add ignored outputs ahbo[hconfig][2][26] -both
add ignored outputs ahbo[hconfig][2][27] -both
add ignored outputs ahbo[hconfig][2][28] -both
add ignored outputs ahbo[hconfig][2][29] -both
add ignored outputs ahbo[hconfig][2][2] -both
add ignored outputs ahbo[hconfig][2][30] -both
add ignored outputs ahbo[hconfig][2][31] -both
add ignored outputs ahbo[hconfig][2][3] -both
add ignored outputs ahbo[hconfig][2][4] -both
add ignored outputs ahbo[hconfig][2][5] -both
add ignored outputs ahbo[hconfig][2][6] -both
add ignored outputs ahbo[hconfig][2][7] -both
add ignored outputs ahbo[hconfig][2][8] -both
add ignored outputs ahbo[hconfig][2][9] -both
add ignored outputs ahbo[hconfig][3][0] -both
add ignored outputs ahbo[hconfig][3][10] -both
add ignored outputs ahbo[hconfig][3][11] -both
add ignored outputs ahbo[hconfig][3][12] -both
add ignored outputs ahbo[hconfig][3][13] -both
add ignored outputs ahbo[hconfig][3][14] -both
add ignored outputs ahbo[hconfig][3][15] -both
add ignored outputs ahbo[hconfig][3][16] -both
add ignored outputs ahbo[hconfig][3][17] -both
add ignored outputs ahbo[hconfig][3][18] -both
add ignored outputs ahbo[hconfig][3][19] -both
add ignored outputs ahbo[hconfig][3][1] -both
add ignored outputs ahbo[hconfig][3][20] -both
add ignored outputs ahbo[hconfig][3][21] -both
add ignored outputs ahbo[hconfig][3][22] -both
add ignored outputs ahbo[hconfig][3][23] -both
add ignored outputs ahbo[hconfig][3][24] -both
add ignored outputs ahbo[hconfig][3][25] -both
add ignored outputs ahbo[hconfig][3][26] -both
add ignored outputs ahbo[hconfig][3][27] -both
add ignored outputs ahbo[hconfig][3][28] -both
add ignored outputs ahbo[hconfig][3][29] -both
add ignored outputs ahbo[hconfig][3][2] -both
add ignored outputs ahbo[hconfig][3][30] -both
add ignored outputs ahbo[hconfig][3][31] -both
add ignored outputs ahbo[hconfig][3][3] -both
add ignored outputs ahbo[hconfig][3][4] -both
add ignored outputs ahbo[hconfig][3][5] -both
add ignored outputs ahbo[hconfig][3][6] -both
add ignored outputs ahbo[hconfig][3][7] -both
add ignored outputs ahbo[hconfig][3][8] -both
add ignored outputs ahbo[hconfig][3][9] -both
add ignored outputs ahbo[hconfig][4][0] -both
add ignored outputs ahbo[hconfig][4][10] -both
add ignored outputs ahbo[hconfig][4][11] -both
add ignored outputs ahbo[hconfig][4][12] -both
add ignored outputs ahbo[hconfig][4][13] -both
add ignored outputs ahbo[hconfig][4][14] -both
add ignored outputs ahbo[hconfig][4][15] -both
add ignored outputs ahbo[hconfig][4][16] -both
add ignored outputs ahbo[hconfig][4][17] -both
add ignored outputs ahbo[hconfig][4][18] -both
add ignored outputs ahbo[hconfig][4][19] -both
add ignored outputs ahbo[hconfig][4][1] -both
add ignored outputs ahbo[hconfig][4][20] -both
add ignored outputs ahbo[hconfig][4][21] -both
add ignored outputs ahbo[hconfig][4][22] -both
add ignored outputs ahbo[hconfig][4][23] -both
add ignored outputs ahbo[hconfig][4][24] -both
add ignored outputs ahbo[hconfig][4][25] -both
add ignored outputs ahbo[hconfig][4][26] -both
add ignored outputs ahbo[hconfig][4][27] -both
add ignored outputs ahbo[hconfig][4][28] -both
add ignored outputs ahbo[hconfig][4][29] -both
add ignored outputs ahbo[hconfig][4][2] -both
add ignored outputs ahbo[hconfig][4][30] -both
add ignored outputs ahbo[hconfig][4][31] -both
add ignored outputs ahbo[hconfig][4][3] -both
add ignored outputs ahbo[hconfig][4][4] -both
add ignored outputs ahbo[hconfig][4][5] -both
add ignored outputs ahbo[hconfig][4][6] -both
add ignored outputs ahbo[hconfig][4][7] -both
add ignored outputs ahbo[hconfig][4][8] -both
add ignored outputs ahbo[hconfig][4][9] -both
add ignored outputs ahbo[hconfig][5][0] -both
add ignored outputs ahbo[hconfig][5][10] -both
add ignored outputs ahbo[hconfig][5][11] -both
add ignored outputs ahbo[hconfig][5][12] -both
add ignored outputs ahbo[hconfig][5][13] -both
add ignored outputs ahbo[hconfig][5][14] -both
add ignored outputs ahbo[hconfig][5][15] -both
add ignored outputs ahbo[hconfig][5][16] -both
add ignored outputs ahbo[hconfig][5][17] -both
add ignored outputs ahbo[hconfig][5][18] -both
add ignored outputs ahbo[hconfig][5][19] -both
add ignored outputs ahbo[hconfig][5][1] -both
add ignored outputs ahbo[hconfig][5][20] -both
add ignored outputs ahbo[hconfig][5][21] -both
add ignored outputs ahbo[hconfig][5][22] -both
add ignored outputs ahbo[hconfig][5][23] -both
add ignored outputs ahbo[hconfig][5][24] -both
add ignored outputs ahbo[hconfig][5][25] -both
add ignored outputs ahbo[hconfig][5][26] -both
add ignored outputs ahbo[hconfig][5][27] -both
add ignored outputs ahbo[hconfig][5][28] -both
add ignored outputs ahbo[hconfig][5][29] -both
add ignored outputs ahbo[hconfig][5][2] -both
add ignored outputs ahbo[hconfig][5][30] -both
add ignored outputs ahbo[hconfig][5][31] -both
add ignored outputs ahbo[hconfig][5][3] -both
add ignored outputs ahbo[hconfig][5][4] -both
add ignored outputs ahbo[hconfig][5][5] -both
add ignored outputs ahbo[hconfig][5][6] -both
add ignored outputs ahbo[hconfig][5][7] -both
add ignored outputs ahbo[hconfig][5][8] -both
add ignored outputs ahbo[hconfig][5][9] -both
add ignored outputs ahbo[hconfig][6][0] -both
add ignored outputs ahbo[hconfig][6][10] -both
add ignored outputs ahbo[hconfig][6][11] -both
add ignored outputs ahbo[hconfig][6][12] -both
add ignored outputs ahbo[hconfig][6][13] -both
add ignored outputs ahbo[hconfig][6][14] -both
add ignored outputs ahbo[hconfig][6][15] -both
add ignored outputs ahbo[hconfig][6][16] -both
add ignored outputs ahbo[hconfig][6][17] -both
add ignored outputs ahbo[hconfig][6][18] -both
add ignored outputs ahbo[hconfig][6][19] -both
add ignored outputs ahbo[hconfig][6][1] -both
add ignored outputs ahbo[hconfig][6][20] -both
add ignored outputs ahbo[hconfig][6][21] -both
add ignored outputs ahbo[hconfig][6][22] -both
add ignored outputs ahbo[hconfig][6][23] -both
add ignored outputs ahbo[hconfig][6][24] -both
add ignored outputs ahbo[hconfig][6][25] -both
add ignored outputs ahbo[hconfig][6][26] -both
add ignored outputs ahbo[hconfig][6][27] -both
add ignored outputs ahbo[hconfig][6][28] -both
add ignored outputs ahbo[hconfig][6][29] -both
add ignored outputs ahbo[hconfig][6][2] -both
add ignored outputs ahbo[hconfig][6][30] -both
add ignored outputs ahbo[hconfig][6][31] -both
add ignored outputs ahbo[hconfig][6][3] -both
add ignored outputs ahbo[hconfig][6][4] -both
add ignored outputs ahbo[hconfig][6][5] -both
add ignored outputs ahbo[hconfig][6][6] -both
add ignored outputs ahbo[hconfig][6][7] -both
add ignored outputs ahbo[hconfig][6][8] -both
add ignored outputs ahbo[hconfig][6][9] -both
add ignored outputs ahbo[hconfig][7][0] -both
add ignored outputs ahbo[hconfig][7][10] -both
add ignored outputs ahbo[hconfig][7][11] -both
add ignored outputs ahbo[hconfig][7][12] -both
add ignored outputs ahbo[hconfig][7][13] -both
add ignored outputs ahbo[hconfig][7][14] -both
add ignored outputs ahbo[hconfig][7][15] -both
add ignored outputs ahbo[hconfig][7][16] -both
add ignored outputs ahbo[hconfig][7][17] -both
add ignored outputs ahbo[hconfig][7][18] -both
add ignored outputs ahbo[hconfig][7][19] -both
add ignored outputs ahbo[hconfig][7][1] -both
add ignored outputs ahbo[hconfig][7][20] -both
add ignored outputs ahbo[hconfig][7][21] -both
add ignored outputs ahbo[hconfig][7][22] -both
add ignored outputs ahbo[hconfig][7][23] -both
add ignored outputs ahbo[hconfig][7][24] -both
add ignored outputs ahbo[hconfig][7][25] -both
add ignored outputs ahbo[hconfig][7][26] -both
add ignored outputs ahbo[hconfig][7][27] -both
add ignored outputs ahbo[hconfig][7][28] -both
add ignored outputs ahbo[hconfig][7][29] -both
add ignored outputs ahbo[hconfig][7][2] -both
add ignored outputs ahbo[hconfig][7][30] -both
add ignored outputs ahbo[hconfig][7][31] -both
add ignored outputs ahbo[hconfig][7][3] -both
add ignored outputs ahbo[hconfig][7][4] -both
add ignored outputs ahbo[hconfig][7][5] -both
add ignored outputs ahbo[hconfig][7][6] -both
add ignored outputs ahbo[hconfig][7][7] -both
add ignored outputs ahbo[hconfig][7][8] -both
add ignored outputs ahbo[hconfig][7][9] -both
add ignored outputs ahbo[hindex][0] -both
add ignored outputs ahbo[hindex][1] -both
add ignored outputs ahbo[hindex][2] -both
add ignored outputs ahbo[hindex][3] -both
add ignored outputs ahbo[hirq][0] -both
add ignored outputs ahbo[hirq][16] -both
add ignored outputs ahbo[hirq][17] -both
add ignored outputs ahbo[hirq][18] -both
add ignored outputs ahbo[hirq][19] -both
add ignored outputs ahbo[hirq][20] -both
add ignored outputs ahbo[hirq][21] -both
add ignored outputs ahbo[hirq][22] -both
add ignored outputs ahbo[hirq][23] -both
add ignored outputs ahbo[hirq][24] -both
add ignored outputs ahbo[hirq][25] -both
add ignored outputs ahbo[hirq][26] -both
add ignored outputs ahbo[hirq][27] -both
add ignored outputs ahbo[hirq][28] -both
add ignored outputs ahbo[hirq][29] -both
add ignored outputs ahbo[hirq][30] -both
add ignored outputs ahbo[hirq][31] -both
add ignored outputs ahbo[hprot][0] -both
add ignored outputs ahbo[hprot][1] -both
add ignored outputs ahbo[hprot][2] -both
add ignored outputs ahbo[hprot][3] -both
add ignored outputs lltckn -both
add ignored outputs tapo_capt -both
add ignored outputs tapo_inst[0] -both
add ignored outputs tapo_inst[1] -both
add ignored outputs tapo_inst[2] -both
add ignored outputs tapo_inst[3] -both
add ignored outputs tapo_inst[4] -both
add ignored outputs tapo_inst[5] -both
add ignored outputs tapo_inst[6] -both
add ignored outputs tapo_inst[7] -both
add ignored outputs tapo_iupd -both
add ignored outputs tapo_ninst[0] -both
add ignored outputs tapo_ninst[1] -both
add ignored outputs tapo_ninst[2] -both
add ignored outputs tapo_ninst[3] -both
add ignored outputs tapo_ninst[4] -both
add ignored outputs tapo_ninst[5] -both
add ignored outputs tapo_ninst[6] -both
add ignored outputs tapo_ninst[7] -both
add ignored outputs tapo_rst -both
add ignored outputs tapo_shft -both
add ignored outputs tapo_tck -both
add ignored outputs tapo_tckn -both
add ignored outputs tapo_tdi -both
add ignored outputs tapo_upd -both
add ignored outputs tdo -both
add ignored outputs tdoen -both
set system mode lec
add compared points -all

// Remove pins that aren't used by the top design

compare
report verification -compare_result
