add ignored outputs ahbso[hconfig][0][10] -both
add ignored outputs ahbso[hconfig][0][13] -both
add ignored outputs ahbso[hconfig][0][15] -both
add ignored outputs ahbso[hconfig][0][17] -both
add ignored outputs ahbso[hconfig][0][19] -both
add ignored outputs ahbso[hconfig][0][20] -both
add ignored outputs ahbso[hconfig][0][21] -both
add ignored outputs ahbso[hconfig][0][22] -both
add ignored outputs ahbso[hconfig][0][23] -both
add ignored outputs ahbso[hconfig][0][25] -both
add ignored outputs ahbso[hconfig][0][26] -both
add ignored outputs ahbso[hconfig][0][27] -both
add ignored outputs ahbso[hconfig][0][28] -both
add ignored outputs ahbso[hconfig][0][29] -both
add ignored outputs ahbso[hconfig][0][30] -both
add ignored outputs ahbso[hconfig][0][31] -both
add ignored outputs ahbso[hconfig][0][3] -both
add ignored outputs ahbso[hconfig][0][4] -both
add ignored outputs ahbso[hconfig][0][6] -both
add ignored outputs ahbso[hconfig][0][7] -both
add ignored outputs ahbso[hconfig][0][8] -both
add ignored outputs ahbso[hconfig][0][9] -both
add ignored outputs ahbso[hconfig][1][10] -both
add ignored outputs ahbso[hconfig][1][11] -both
add ignored outputs ahbso[hconfig][1][17] -both
add ignored outputs ahbso[hconfig][1][28] -both
add ignored outputs ahbso[hconfig][1][29] -both
add ignored outputs ahbso[hconfig][1][31] -both
add ignored outputs ahbso[hconfig][1][4] -both
add ignored outputs ahbso[hconfig][1][5] -both
add ignored outputs ahbso[hconfig][1][9] -both
add ignored outputs ahbso[hconfig][2][10] -both
add ignored outputs ahbso[hconfig][2][12] -both
add ignored outputs ahbso[hconfig][2][13] -both
add ignored outputs ahbso[hconfig][2][14] -both
add ignored outputs ahbso[hconfig][2][15] -both
add ignored outputs ahbso[hconfig][2][16] -both
add ignored outputs ahbso[hconfig][2][17] -both
add ignored outputs ahbso[hconfig][2][1] -both
add ignored outputs ahbso[hconfig][2][24] -both
add ignored outputs ahbso[hconfig][2][28] -both
add ignored outputs ahbso[hconfig][2][29] -both
add ignored outputs ahbso[hconfig][2][31] -both
add ignored outputs ahbso[hconfig][2][4] -both
add ignored outputs ahbso[hconfig][2][5] -both
add ignored outputs ahbso[hconfig][2][6] -both
add ignored outputs ahbso[hconfig][2][7] -both
add ignored outputs ahbso[hconfig][2][8] -both
add ignored outputs ahbso[hconfig][2][9] -both
add ignored outputs ahbso[hconfig][3][0] -both
add ignored outputs ahbso[hconfig][3][10] -both
add ignored outputs ahbso[hconfig][3][11] -both
add ignored outputs ahbso[hconfig][3][17] -both
add ignored outputs ahbso[hconfig][3][18] -both
add ignored outputs ahbso[hconfig][3][19] -both
add ignored outputs ahbso[hconfig][3][1] -both
add ignored outputs ahbso[hconfig][3][20] -both
add ignored outputs ahbso[hconfig][3][21] -both
add ignored outputs ahbso[hconfig][3][22] -both
add ignored outputs ahbso[hconfig][3][23] -both
add ignored outputs ahbso[hconfig][3][25] -both
add ignored outputs ahbso[hconfig][3][26] -both
add ignored outputs ahbso[hconfig][3][27] -both
add ignored outputs ahbso[hconfig][3][28] -both
add ignored outputs ahbso[hconfig][3][29] -both
add ignored outputs ahbso[hconfig][3][2] -both
add ignored outputs ahbso[hconfig][3][30] -both
add ignored outputs ahbso[hconfig][3][31] -both
add ignored outputs ahbso[hconfig][3][3] -both
add ignored outputs ahbso[hconfig][3][4] -both
add ignored outputs ahbso[hconfig][3][9] -both
add ignored outputs ahbso[hconfig][4][18] -both
add ignored outputs ahbso[hconfig][4][19] -both
add ignored outputs ahbso[hconfig][4][1] -both
add ignored outputs ahbso[hconfig][4][28] -both
add ignored outputs ahbso[hconfig][4][29] -both
add ignored outputs ahbso[hconfig][4][2] -both
add ignored outputs ahbso[hconfig][4][3] -both
add ignored outputs ahbso[hconfig][6][17] -both
add ignored outputs ahbso[hconfig][6][1] -both
add ignored outputs ahbso[hconfig][6][28] -both
add ignored outputs ahbso[hconfig][6][29] -both
add ignored outputs ahbso[hconfig][6][31] -both
add ignored outputs ahbso[hconfig][7][18] -both
add ignored outputs ahbso[hconfig][7][19] -both
add ignored outputs ahbso[hconfig][7][20] -both
add ignored outputs ahbso[hconfig][7][21] -both
add ignored outputs ahbso[hconfig][7][22] -both
add ignored outputs ahbso[hconfig][7][23] -both
add ignored outputs ahbso[hconfig][7][24] -both
add ignored outputs ahbso[hconfig][7][25] -both
add ignored outputs ahbso[hconfig][7][26] -both
add ignored outputs ahbso[hconfig][7][27] -both
add ignored outputs ahbso[hconfig][7][2] -both
add ignored outputs ahbso[hconfig][7][30] -both
add ignored outputs ahbso[hconfig][7][3] -both
add ignored outputs ahbso[hindex][0] -both
add ignored outputs ahbso[hindex][1] -both
add ignored outputs ahbso[hindex][2] -both
add ignored outputs ahbso[hindex][3] -both
add ignored outputs ahbso[hirq][0] -both
add ignored outputs ahbso[hirq][16] -both
add ignored outputs ahbso[hirq][17] -both
add ignored outputs ahbso[hirq][18] -both
add ignored outputs ahbso[hirq][19] -both
add ignored outputs ahbso[hirq][20] -both
add ignored outputs ahbso[hirq][21] -both
add ignored outputs ahbso[hirq][22] -both
add ignored outputs ahbso[hirq][23] -both
add ignored outputs ahbso[hirq][24] -both
add ignored outputs ahbso[hirq][25] -both
add ignored outputs ahbso[hirq][26] -both
add ignored outputs ahbso[hirq][27] -both
add ignored outputs ahbso[hirq][28] -both
add ignored outputs ahbso[hirq][29] -both
add ignored outputs ahbso[hirq][30] -both
add ignored outputs ahbso[hirq][31] -both
add ignored outputs ahbso[hsplit][0] -both
add ignored outputs ahbso[hsplit][10] -both
add ignored outputs ahbso[hsplit][11] -both
add ignored outputs ahbso[hsplit][12] -both
add ignored outputs ahbso[hsplit][13] -both
add ignored outputs ahbso[hsplit][14] -both
add ignored outputs ahbso[hsplit][15] -both
add ignored outputs ahbso[hsplit][1] -both
add ignored outputs ahbso[hsplit][2] -both
add ignored outputs ahbso[hsplit][3] -both
add ignored outputs ahbso[hsplit][4] -both
add ignored outputs ahbso[hsplit][5] -both
add ignored outputs ahbso[hsplit][6] -both
add ignored outputs ahbso[hsplit][7] -both
add ignored outputs ahbso[hsplit][8] -both
add ignored outputs ahbso[hsplit][9] -both
add ignored outputs spio[cdcsnoen] -both
add ignored outputs spio[initialized] -both
add ignored outputs spio[mosioen] -both
add ignored outputs spio[ready] -both
set system mode lec
add compared points -all

// Remove pins that aren't used by the top design

compare
report verification -compare_result
