add_ignored_outputs {ahbo[hconfig][0][10]} -both
add_ignored_outputs {ahbo[hconfig][0][11]} -both
add_ignored_outputs {ahbo[hconfig][0][16]} -both
add_ignored_outputs {ahbo[hconfig][0][17]} -both
add_ignored_outputs {ahbo[hconfig][0][18]} -both
add_ignored_outputs {ahbo[hconfig][0][19]} -both
add_ignored_outputs {ahbo[hconfig][0][1]} -both
add_ignored_outputs {ahbo[hconfig][0][20]} -both
add_ignored_outputs {ahbo[hconfig][0][21]} -both
add_ignored_outputs {ahbo[hconfig][0][22]} -both
add_ignored_outputs {ahbo[hconfig][0][23]} -both
add_ignored_outputs {ahbo[hconfig][0][25]} -both
add_ignored_outputs {ahbo[hconfig][0][26]} -both
add_ignored_outputs {ahbo[hconfig][0][27]} -both
add_ignored_outputs {ahbo[hconfig][0][28]} -both
add_ignored_outputs {ahbo[hconfig][0][29]} -both
add_ignored_outputs {ahbo[hconfig][0][2]} -both
add_ignored_outputs {ahbo[hconfig][0][30]} -both
add_ignored_outputs {ahbo[hconfig][0][31]} -both
add_ignored_outputs {ahbo[hconfig][0][3]} -both
add_ignored_outputs {ahbo[hconfig][0][4]} -both
add_ignored_outputs {ahbo[hconfig][0][6]} -both
add_ignored_outputs {ahbo[hconfig][0][9]} -both
add_ignored_outputs {ahbo[hconfig][1][0]} -both
add_ignored_outputs {ahbo[hconfig][1][17]} -both
add_ignored_outputs {ahbo[hconfig][1][19]} -both
add_ignored_outputs {ahbo[hconfig][1][20]} -both
add_ignored_outputs {ahbo[hconfig][1][21]} -both
add_ignored_outputs {ahbo[hconfig][1][22]} -both
add_ignored_outputs {ahbo[hconfig][1][23]} -both
add_ignored_outputs {ahbo[hconfig][1][25]} -both
add_ignored_outputs {ahbo[hconfig][1][27]} -both
add_ignored_outputs {ahbo[hconfig][1][3]} -both
add_ignored_outputs {ahbo[hconfig][2][0]} -both
add_ignored_outputs {ahbo[hconfig][2][10]} -both
add_ignored_outputs {ahbo[hconfig][2][11]} -both
add_ignored_outputs {ahbo[hconfig][2][15]} -both
add_ignored_outputs {ahbo[hconfig][2][16]} -both
add_ignored_outputs {ahbo[hconfig][2][18]} -both
add_ignored_outputs {ahbo[hconfig][2][1]} -both
add_ignored_outputs {ahbo[hconfig][2][26]} -both
add_ignored_outputs {ahbo[hconfig][2][28]} -both
add_ignored_outputs {ahbo[hconfig][2][29]} -both
add_ignored_outputs {ahbo[hconfig][2][2]} -both
add_ignored_outputs {ahbo[hconfig][2][30]} -both
add_ignored_outputs {ahbo[hconfig][2][31]} -both
add_ignored_outputs {ahbo[hconfig][2][4]} -both
add_ignored_outputs {ahbo[hconfig][2][5]} -both
add_ignored_outputs {ahbo[hconfig][2][6]} -both
add_ignored_outputs {ahbo[hconfig][2][7]} -both
add_ignored_outputs {ahbo[hconfig][2][8]} -both
add_ignored_outputs {ahbo[hconfig][2][9]} -both
add_ignored_outputs {ahbo[hconfig][3][12]} -both
add_ignored_outputs {ahbo[hconfig][3][13]} -both
add_ignored_outputs {ahbo[hconfig][3][14]} -both
add_ignored_outputs {ahbo[hconfig][3][24]} -both
add_ignored_outputs {ahbo[hconfig][3][5]} -both
add_ignored_outputs {ahbo[hconfig][4][18]} -both
add_ignored_outputs {ahbo[hconfig][4][19]} -both
add_ignored_outputs {ahbo[hconfig][4][2]} -both
add_ignored_outputs {ahbo[hconfig][4][3]} -both
add_ignored_outputs {ahbo[hconfig][5][19]} -both
add_ignored_outputs {ahbo[hconfig][5][20]} -both
add_ignored_outputs {ahbo[hconfig][5][21]} -both
add_ignored_outputs {ahbo[hconfig][5][22]} -both
add_ignored_outputs {ahbo[hconfig][5][23]} -both
add_ignored_outputs {ahbo[hconfig][5][25]} -both
add_ignored_outputs {ahbo[hconfig][5][27]} -both
add_ignored_outputs {ahbo[hconfig][5][30]} -both
add_ignored_outputs {ahbo[hconfig][5][3]} -both
add_ignored_outputs {ahbo[hconfig][6][18]} -both
add_ignored_outputs {ahbo[hconfig][6][24]} -both
add_ignored_outputs {ahbo[hconfig][6][26]} -both
add_ignored_outputs {ahbo[hconfig][6][28]} -both
add_ignored_outputs {ahbo[hconfig][6][29]} -both
add_ignored_outputs {ahbo[hconfig][6][2]} -both
add_ignored_outputs {ahbo[hconfig][6][31]} -both
add_ignored_outputs {ahbo[hconfig][7][17]} -both
add_ignored_outputs {ahbo[hconfig][7][1]} -both
add_ignored_outputs {ahbo[hindex][0]} -both
add_ignored_outputs {ahbo[hindex][1]} -both
add_ignored_outputs {ahbo[hindex][2]} -both
add_ignored_outputs {ahbo[hindex][3]} -both
add_ignored_outputs {ahbo[hirq][0]} -both
add_ignored_outputs {ahbo[hirq][7]} -both
add_ignored_outputs {ahbo[hsplit][0]} -both
add_ignored_outputs {ahbo[hsplit][10]} -both
add_ignored_outputs {ahbo[hsplit][11]} -both
add_ignored_outputs {ahbo[hsplit][12]} -both
add_ignored_outputs {ahbo[hsplit][13]} -both
add_ignored_outputs {ahbo[hsplit][14]} -both
add_ignored_outputs {ahbo[hsplit][15]} -both
add_ignored_outputs {ahbo[hsplit][1]} -both
add_ignored_outputs {ahbo[hsplit][2]} -both
add_ignored_outputs {ahbo[hsplit][3]} -both
add_ignored_outputs {ahbo[hsplit][4]} -both
add_ignored_outputs {ahbo[hsplit][5]} -both
add_ignored_outputs {ahbo[hsplit][6]} -both
add_ignored_outputs {ahbo[hsplit][7]} -both
add_ignored_outputs {ahbo[hsplit][8]} -both
add_ignored_outputs {ahbo[hsplit][9]} -both
add_ignored_outputs {apbi[paddr][0]} -both
add_ignored_outputs {apbi[paddr][10]} -both
add_ignored_outputs {apbi[paddr][11]} -both
add_ignored_outputs {apbi[paddr][12]} -both
add_ignored_outputs {apbi[paddr][13]} -both
add_ignored_outputs {apbi[paddr][14]} -both
add_ignored_outputs {apbi[paddr][15]} -both
add_ignored_outputs {apbi[paddr][16]} -both
add_ignored_outputs {apbi[paddr][17]} -both
add_ignored_outputs {apbi[paddr][18]} -both
add_ignored_outputs {apbi[paddr][19]} -both
add_ignored_outputs {apbi[paddr][1]} -both
add_ignored_outputs {apbi[paddr][20]} -both
add_ignored_outputs {apbi[paddr][21]} -both
add_ignored_outputs {apbi[paddr][22]} -both
add_ignored_outputs {apbi[paddr][23]} -both
add_ignored_outputs {apbi[paddr][24]} -both
add_ignored_outputs {apbi[paddr][25]} -both
add_ignored_outputs {apbi[paddr][26]} -both
add_ignored_outputs {apbi[paddr][27]} -both
add_ignored_outputs {apbi[paddr][28]} -both
add_ignored_outputs {apbi[paddr][29]} -both
add_ignored_outputs {apbi[paddr][2]} -both
add_ignored_outputs {apbi[paddr][30]} -both
add_ignored_outputs {apbi[paddr][31]} -both
add_ignored_outputs {apbi[paddr][3]} -both
add_ignored_outputs {apbi[paddr][4]} -both
add_ignored_outputs {apbi[paddr][5]} -both
add_ignored_outputs {apbi[paddr][6]} -both
add_ignored_outputs {apbi[paddr][7]} -both
add_ignored_outputs {apbi[paddr][8]} -both
add_ignored_outputs {apbi[paddr][9]} -both
add_ignored_outputs {apbi[penable]} -both
add_ignored_outputs {apbi[pirq][0]} -both
add_ignored_outputs {apbi[pirq][10]} -both
add_ignored_outputs {apbi[pirq][11]} -both
add_ignored_outputs {apbi[pirq][12]} -both
add_ignored_outputs {apbi[pirq][13]} -both
add_ignored_outputs {apbi[pirq][14]} -both
add_ignored_outputs {apbi[pirq][15]} -both
add_ignored_outputs {apbi[pirq][16]} -both
add_ignored_outputs {apbi[pirq][17]} -both
add_ignored_outputs {apbi[pirq][18]} -both
add_ignored_outputs {apbi[pirq][19]} -both
add_ignored_outputs {apbi[pirq][1]} -both
add_ignored_outputs {apbi[pirq][20]} -both
add_ignored_outputs {apbi[pirq][21]} -both
add_ignored_outputs {apbi[pirq][22]} -both
add_ignored_outputs {apbi[pirq][23]} -both
add_ignored_outputs {apbi[pirq][24]} -both
add_ignored_outputs {apbi[pirq][25]} -both
add_ignored_outputs {apbi[pirq][26]} -both
add_ignored_outputs {apbi[pirq][27]} -both
add_ignored_outputs {apbi[pirq][28]} -both
add_ignored_outputs {apbi[pirq][29]} -both
add_ignored_outputs {apbi[pirq][2]} -both
add_ignored_outputs {apbi[pirq][30]} -both
add_ignored_outputs {apbi[pirq][31]} -both
add_ignored_outputs {apbi[pirq][3]} -both
add_ignored_outputs {apbi[pirq][4]} -both
add_ignored_outputs {apbi[pirq][5]} -both
add_ignored_outputs {apbi[pirq][6]} -both
add_ignored_outputs {apbi[pirq][7]} -both
add_ignored_outputs {apbi[pirq][8]} -both
add_ignored_outputs {apbi[pirq][9]} -both
add_ignored_outputs {apbi[psel][0]} -both
add_ignored_outputs {apbi[psel][10]} -both
add_ignored_outputs {apbi[psel][11]} -both
add_ignored_outputs {apbi[psel][12]} -both
add_ignored_outputs {apbi[psel][13]} -both
add_ignored_outputs {apbi[psel][14]} -both
add_ignored_outputs {apbi[psel][15]} -both
add_ignored_outputs {apbi[psel][1]} -both
add_ignored_outputs {apbi[psel][2]} -both
add_ignored_outputs {apbi[psel][3]} -both
add_ignored_outputs {apbi[psel][4]} -both
add_ignored_outputs {apbi[psel][5]} -both
add_ignored_outputs {apbi[psel][6]} -both
add_ignored_outputs {apbi[psel][7]} -both
add_ignored_outputs {apbi[psel][8]} -both
add_ignored_outputs {apbi[psel][9]} -both
add_ignored_outputs {apbi[pwdata][0]} -both
add_ignored_outputs {apbi[pwdata][10]} -both
add_ignored_outputs {apbi[pwdata][11]} -both
add_ignored_outputs {apbi[pwdata][12]} -both
add_ignored_outputs {apbi[pwdata][13]} -both
add_ignored_outputs {apbi[pwdata][14]} -both
add_ignored_outputs {apbi[pwdata][15]} -both
add_ignored_outputs {apbi[pwdata][16]} -both
add_ignored_outputs {apbi[pwdata][17]} -both
add_ignored_outputs {apbi[pwdata][18]} -both
add_ignored_outputs {apbi[pwdata][19]} -both
add_ignored_outputs {apbi[pwdata][1]} -both
add_ignored_outputs {apbi[pwdata][20]} -both
add_ignored_outputs {apbi[pwdata][21]} -both
add_ignored_outputs {apbi[pwdata][22]} -both
add_ignored_outputs {apbi[pwdata][23]} -both
add_ignored_outputs {apbi[pwdata][24]} -both
add_ignored_outputs {apbi[pwdata][25]} -both
add_ignored_outputs {apbi[pwdata][26]} -both
add_ignored_outputs {apbi[pwdata][27]} -both
add_ignored_outputs {apbi[pwdata][28]} -both
add_ignored_outputs {apbi[pwdata][29]} -both
add_ignored_outputs {apbi[pwdata][2]} -both
add_ignored_outputs {apbi[pwdata][30]} -both
add_ignored_outputs {apbi[pwdata][31]} -both
add_ignored_outputs {apbi[pwdata][3]} -both
add_ignored_outputs {apbi[pwdata][4]} -both
add_ignored_outputs {apbi[pwdata][5]} -both
add_ignored_outputs {apbi[pwdata][6]} -both
add_ignored_outputs {apbi[pwdata][7]} -both
add_ignored_outputs {apbi[pwdata][8]} -both
add_ignored_outputs {apbi[pwdata][9]} -both
add_ignored_outputs {apbi[pwrite]} -both
add_ignored_outputs {apbi[scanen]} -both
add_ignored_outputs {apbi[testen]} -both
add_ignored_outputs {apbi[testin][0]} -both
add_ignored_outputs {apbi[testin][1]} -both
add_ignored_outputs {apbi[testin][2]} -both
add_ignored_outputs {apbi[testin][3]} -both
add_ignored_outputs {apbi[testoen]} -both
add_ignored_outputs {apbi[testrst]} -both
set_system_mode lec
add_compared_points -all

// Remove pins that aren't used by the top design

compare
report_verification -compare_result
exit
