add_ignored_outputs {ahbso[hconfig][0][10]} -both
add_ignored_outputs {ahbso[hconfig][0][11]} -both
add_ignored_outputs {ahbso[hconfig][0][12]} -both
add_ignored_outputs {ahbso[hconfig][0][13]} -both
add_ignored_outputs {ahbso[hconfig][0][15]} -both
add_ignored_outputs {ahbso[hconfig][0][16]} -both
add_ignored_outputs {ahbso[hconfig][0][17]} -both
add_ignored_outputs {ahbso[hconfig][0][18]} -both
add_ignored_outputs {ahbso[hconfig][0][19]} -both
add_ignored_outputs {ahbso[hconfig][0][20]} -both
add_ignored_outputs {ahbso[hconfig][0][21]} -both
add_ignored_outputs {ahbso[hconfig][0][22]} -both
add_ignored_outputs {ahbso[hconfig][0][23]} -both
add_ignored_outputs {ahbso[hconfig][0][25]} -both
add_ignored_outputs {ahbso[hconfig][0][26]} -both
add_ignored_outputs {ahbso[hconfig][0][27]} -both
add_ignored_outputs {ahbso[hconfig][0][28]} -both
add_ignored_outputs {ahbso[hconfig][0][30]} -both
add_ignored_outputs {ahbso[hconfig][0][31]} -both
add_ignored_outputs {ahbso[hconfig][0][3]} -both
add_ignored_outputs {ahbso[hconfig][0][4]} -both
add_ignored_outputs {ahbso[hconfig][0][7]} -both
add_ignored_outputs {ahbso[hconfig][0][8]} -both
add_ignored_outputs {ahbso[hconfig][0][9]} -both
add_ignored_outputs {ahbso[hconfig][1][29]} -both
add_ignored_outputs {ahbso[hconfig][2][0]} -both
add_ignored_outputs {ahbso[hconfig][2][12]} -both
add_ignored_outputs {ahbso[hconfig][2][13]} -both
add_ignored_outputs {ahbso[hconfig][2][14]} -both
add_ignored_outputs {ahbso[hconfig][2][15]} -both
add_ignored_outputs {ahbso[hconfig][2][16]} -both
add_ignored_outputs {ahbso[hconfig][2][18]} -both
add_ignored_outputs {ahbso[hconfig][2][1]} -both
add_ignored_outputs {ahbso[hconfig][2][24]} -both
add_ignored_outputs {ahbso[hconfig][2][29]} -both
add_ignored_outputs {ahbso[hconfig][2][30]} -both
add_ignored_outputs {ahbso[hconfig][2][5]} -both
add_ignored_outputs {ahbso[hconfig][2][6]} -both
add_ignored_outputs {ahbso[hconfig][2][7]} -both
add_ignored_outputs {ahbso[hconfig][2][8]} -both
add_ignored_outputs {ahbso[hconfig][3][10]} -both
add_ignored_outputs {ahbso[hconfig][3][11]} -both
add_ignored_outputs {ahbso[hconfig][3][17]} -both
add_ignored_outputs {ahbso[hconfig][3][19]} -both
add_ignored_outputs {ahbso[hconfig][3][20]} -both
add_ignored_outputs {ahbso[hconfig][3][21]} -both
add_ignored_outputs {ahbso[hconfig][3][22]} -both
add_ignored_outputs {ahbso[hconfig][3][23]} -both
add_ignored_outputs {ahbso[hconfig][3][25]} -both
add_ignored_outputs {ahbso[hconfig][3][26]} -both
add_ignored_outputs {ahbso[hconfig][3][27]} -both
add_ignored_outputs {ahbso[hconfig][3][28]} -both
add_ignored_outputs {ahbso[hconfig][3][2]} -both
add_ignored_outputs {ahbso[hconfig][3][31]} -both
add_ignored_outputs {ahbso[hconfig][3][3]} -both
add_ignored_outputs {ahbso[hconfig][3][4]} -both
add_ignored_outputs {ahbso[hconfig][3][9]} -both
add_ignored_outputs {ahbso[hconfig][4][18]} -both
add_ignored_outputs {ahbso[hconfig][4][19]} -both
add_ignored_outputs {ahbso[hconfig][4][20]} -both
add_ignored_outputs {ahbso[hconfig][4][21]} -both
add_ignored_outputs {ahbso[hconfig][4][22]} -both
add_ignored_outputs {ahbso[hconfig][4][23]} -both
add_ignored_outputs {ahbso[hconfig][4][24]} -both
add_ignored_outputs {ahbso[hconfig][4][25]} -both
add_ignored_outputs {ahbso[hconfig][4][26]} -both
add_ignored_outputs {ahbso[hconfig][4][27]} -both
add_ignored_outputs {ahbso[hconfig][4][2]} -both
add_ignored_outputs {ahbso[hconfig][4][3]} -both
add_ignored_outputs {ahbso[hconfig][6][17]} -both
add_ignored_outputs {ahbso[hconfig][6][18]} -both
add_ignored_outputs {ahbso[hconfig][6][1]} -both
add_ignored_outputs {ahbso[hconfig][6][24]} -both
add_ignored_outputs {ahbso[hconfig][6][28]} -both
add_ignored_outputs {ahbso[hconfig][6][29]} -both
add_ignored_outputs {ahbso[hconfig][6][2]} -both
add_ignored_outputs {ahbso[hconfig][6][30]} -both
add_ignored_outputs {ahbso[hconfig][6][31]} -both
add_ignored_outputs {ahbso[hconfig][7][19]} -both
add_ignored_outputs {ahbso[hconfig][7][20]} -both
add_ignored_outputs {ahbso[hconfig][7][21]} -both
add_ignored_outputs {ahbso[hconfig][7][22]} -both
add_ignored_outputs {ahbso[hconfig][7][23]} -both
add_ignored_outputs {ahbso[hconfig][7][25]} -both
add_ignored_outputs {ahbso[hconfig][7][26]} -both
add_ignored_outputs {ahbso[hconfig][7][27]} -both
add_ignored_outputs {ahbso[hconfig][7][3]} -both
add_ignored_outputs {ahbso[hindex][0]} -both
add_ignored_outputs {ahbso[hindex][1]} -both
add_ignored_outputs {ahbso[hindex][2]} -both
add_ignored_outputs {ahbso[hindex][3]} -both
add_ignored_outputs {ahbso[hirq][0]} -both
add_ignored_outputs {ahbso[hirq][16]} -both
add_ignored_outputs {ahbso[hirq][17]} -both
add_ignored_outputs {ahbso[hirq][18]} -both
add_ignored_outputs {ahbso[hirq][19]} -both
add_ignored_outputs {ahbso[hirq][20]} -both
add_ignored_outputs {ahbso[hirq][21]} -both
add_ignored_outputs {ahbso[hirq][22]} -both
add_ignored_outputs {ahbso[hirq][23]} -both
add_ignored_outputs {ahbso[hirq][24]} -both
add_ignored_outputs {ahbso[hirq][25]} -both
add_ignored_outputs {ahbso[hirq][26]} -both
add_ignored_outputs {ahbso[hirq][27]} -both
add_ignored_outputs {ahbso[hirq][28]} -both
add_ignored_outputs {ahbso[hirq][29]} -both
add_ignored_outputs {ahbso[hirq][30]} -both
add_ignored_outputs {ahbso[hirq][31]} -both
add_ignored_outputs {ahbso[hsplit][0]} -both
add_ignored_outputs {ahbso[hsplit][10]} -both
add_ignored_outputs {ahbso[hsplit][11]} -both
add_ignored_outputs {ahbso[hsplit][12]} -both
add_ignored_outputs {ahbso[hsplit][13]} -both
add_ignored_outputs {ahbso[hsplit][14]} -both
add_ignored_outputs {ahbso[hsplit][15]} -both
add_ignored_outputs {ahbso[hsplit][1]} -both
add_ignored_outputs {ahbso[hsplit][2]} -both
add_ignored_outputs {ahbso[hsplit][3]} -both
add_ignored_outputs {ahbso[hsplit][4]} -both
add_ignored_outputs {ahbso[hsplit][5]} -both
add_ignored_outputs {ahbso[hsplit][6]} -both
add_ignored_outputs {ahbso[hsplit][7]} -both
add_ignored_outputs {ahbso[hsplit][8]} -both
add_ignored_outputs {ahbso[hsplit][9]} -both
add_ignored_outputs {dbgo[0][timer][62]} -both
add_ignored_outputs {dbgo[0][timer][63]} -both
add_ignored_outputs {dbgo[1][timer][62]} -both
add_ignored_outputs {dbgo[1][timer][63]} -both
add_ignored_outputs {dbgo[2][timer][62]} -both
add_ignored_outputs {dbgo[2][timer][63]} -both
add_ignored_outputs {dbgo[3][timer][62]} -both
add_ignored_outputs {dbgo[3][timer][63]} -both
add_ignored_outputs {dsuo[astat][busy]} -both
add_ignored_outputs {dsuo[astat][hmaster][0]} -both
add_ignored_outputs {dsuo[astat][hmaster][1]} -both
add_ignored_outputs {dsuo[astat][hmaster][2]} -both
add_ignored_outputs {dsuo[astat][hmaster][3]} -both
add_ignored_outputs {dsuo[astat][hsize][0]} -both
add_ignored_outputs {dsuo[astat][hsize][1]} -both
add_ignored_outputs {dsuo[astat][hsize][2]} -both
add_ignored_outputs {dsuo[astat][hsize][3]} -both
add_ignored_outputs {dsuo[astat][hsize][4]} -both
add_ignored_outputs {dsuo[astat][hsize][5]} -both
add_ignored_outputs {dsuo[astat][idle]} -both
add_ignored_outputs {dsuo[astat][locked]} -both
add_ignored_outputs {dsuo[astat][nseq]} -both
add_ignored_outputs {dsuo[astat][read]} -both
add_ignored_outputs {dsuo[astat][retry]} -both
add_ignored_outputs {dsuo[astat][seq]} -both
add_ignored_outputs {dsuo[astat][spdel]} -both
add_ignored_outputs {dsuo[astat][split]} -both
add_ignored_outputs {dsuo[astat][write]} -both
add_ignored_outputs {dsuo[astat][ws]} -both
add_ignored_outputs {dsuo[pwd][0]} -both
add_ignored_outputs {dsuo[pwd][10]} -both
add_ignored_outputs {dsuo[pwd][11]} -both
add_ignored_outputs {dsuo[pwd][12]} -both
add_ignored_outputs {dsuo[pwd][13]} -both
add_ignored_outputs {dsuo[pwd][14]} -both
add_ignored_outputs {dsuo[pwd][15]} -both
add_ignored_outputs {dsuo[pwd][1]} -both
add_ignored_outputs {dsuo[pwd][2]} -both
add_ignored_outputs {dsuo[pwd][3]} -both
add_ignored_outputs {dsuo[pwd][4]} -both
add_ignored_outputs {dsuo[pwd][5]} -both
add_ignored_outputs {dsuo[pwd][6]} -both
add_ignored_outputs {dsuo[pwd][7]} -both
add_ignored_outputs {dsuo[pwd][8]} -both
add_ignored_outputs {dsuo[pwd][9]} -both
set_system_mode lec
add_compared_points -all

// Remove pins that aren't used by the top design

compare
report_verification -compare_result
exit
