add_ignored_outputs {apbo[pconfig][0][1]} -both
add_ignored_outputs {apbo[pconfig][1][18]} -both
add_ignored_outputs {apbo[pconfig][1][30]} -both
add_ignored_outputs {apbo[pconfig][1][3]} -both
add_ignored_outputs {apbo[pindex][0]} -both
add_ignored_outputs {apbo[pindex][1]} -both
add_ignored_outputs {apbo[pindex][2]} -both
add_ignored_outputs {apbo[pindex][3]} -both
add_ignored_outputs {apbo[pirq][0]} -both
add_ignored_outputs {apbo[pirq][16]} -both
add_ignored_outputs {apbo[pirq][17]} -both
add_ignored_outputs {apbo[pirq][18]} -both
add_ignored_outputs {apbo[pirq][19]} -both
add_ignored_outputs {apbo[pirq][20]} -both
add_ignored_outputs {apbo[pirq][21]} -both
add_ignored_outputs {apbo[pirq][22]} -both
add_ignored_outputs {apbo[pirq][23]} -both
add_ignored_outputs {apbo[pirq][24]} -both
add_ignored_outputs {apbo[pirq][25]} -both
add_ignored_outputs {apbo[pirq][26]} -both
add_ignored_outputs {apbo[pirq][27]} -both
add_ignored_outputs {apbo[pirq][28]} -both
add_ignored_outputs {apbo[pirq][29]} -both
add_ignored_outputs {apbo[pirq][30]} -both
add_ignored_outputs {apbo[pirq][31]} -both
add_ignored_outputs {irqo[0][index][0]} -both
add_ignored_outputs {irqo[0][index][1]} -both
add_ignored_outputs {irqo[0][index][2]} -both
add_ignored_outputs {irqo[0][index][3]} -both
add_ignored_outputs {irqo[0][rstvec][12]} -both
add_ignored_outputs {irqo[0][rstvec][13]} -both
add_ignored_outputs {irqo[0][rstvec][14]} -both
add_ignored_outputs {irqo[0][rstvec][15]} -both
add_ignored_outputs {irqo[0][rstvec][16]} -both
add_ignored_outputs {irqo[0][rstvec][17]} -both
add_ignored_outputs {irqo[0][rstvec][18]} -both
add_ignored_outputs {irqo[0][rstvec][19]} -both
add_ignored_outputs {irqo[0][rstvec][20]} -both
add_ignored_outputs {irqo[0][rstvec][21]} -both
add_ignored_outputs {irqo[0][rstvec][22]} -both
add_ignored_outputs {irqo[0][rstvec][23]} -both
add_ignored_outputs {irqo[0][rstvec][24]} -both
add_ignored_outputs {irqo[0][rstvec][25]} -both
add_ignored_outputs {irqo[0][rstvec][26]} -both
add_ignored_outputs {irqo[0][rstvec][27]} -both
add_ignored_outputs {irqo[0][rstvec][28]} -both
add_ignored_outputs {irqo[0][rstvec][29]} -both
add_ignored_outputs {irqo[0][rstvec][30]} -both
add_ignored_outputs {irqo[0][rstvec][31]} -both
add_ignored_outputs {irqo[1][index][0]} -both
add_ignored_outputs {irqo[1][index][1]} -both
add_ignored_outputs {irqo[1][index][2]} -both
add_ignored_outputs {irqo[1][index][3]} -both
add_ignored_outputs {irqo[1][rstvec][12]} -both
add_ignored_outputs {irqo[1][rstvec][13]} -both
add_ignored_outputs {irqo[1][rstvec][14]} -both
add_ignored_outputs {irqo[1][rstvec][15]} -both
add_ignored_outputs {irqo[1][rstvec][16]} -both
add_ignored_outputs {irqo[1][rstvec][17]} -both
add_ignored_outputs {irqo[1][rstvec][18]} -both
add_ignored_outputs {irqo[1][rstvec][19]} -both
add_ignored_outputs {irqo[1][rstvec][20]} -both
add_ignored_outputs {irqo[1][rstvec][21]} -both
add_ignored_outputs {irqo[1][rstvec][22]} -both
add_ignored_outputs {irqo[1][rstvec][23]} -both
add_ignored_outputs {irqo[1][rstvec][24]} -both
add_ignored_outputs {irqo[1][rstvec][25]} -both
add_ignored_outputs {irqo[1][rstvec][26]} -both
add_ignored_outputs {irqo[1][rstvec][27]} -both
add_ignored_outputs {irqo[1][rstvec][28]} -both
add_ignored_outputs {irqo[1][rstvec][29]} -both
add_ignored_outputs {irqo[1][rstvec][30]} -both
add_ignored_outputs {irqo[1][rstvec][31]} -both
add_ignored_outputs {irqo[2][index][0]} -both
add_ignored_outputs {irqo[2][index][1]} -both
add_ignored_outputs {irqo[2][index][2]} -both
add_ignored_outputs {irqo[2][index][3]} -both
add_ignored_outputs {irqo[2][rstvec][12]} -both
add_ignored_outputs {irqo[2][rstvec][13]} -both
add_ignored_outputs {irqo[2][rstvec][14]} -both
add_ignored_outputs {irqo[2][rstvec][15]} -both
add_ignored_outputs {irqo[2][rstvec][16]} -both
add_ignored_outputs {irqo[2][rstvec][17]} -both
add_ignored_outputs {irqo[2][rstvec][18]} -both
add_ignored_outputs {irqo[2][rstvec][19]} -both
add_ignored_outputs {irqo[2][rstvec][20]} -both
add_ignored_outputs {irqo[2][rstvec][21]} -both
add_ignored_outputs {irqo[2][rstvec][22]} -both
add_ignored_outputs {irqo[2][rstvec][23]} -both
add_ignored_outputs {irqo[2][rstvec][24]} -both
add_ignored_outputs {irqo[2][rstvec][25]} -both
add_ignored_outputs {irqo[2][rstvec][26]} -both
add_ignored_outputs {irqo[2][rstvec][27]} -both
add_ignored_outputs {irqo[2][rstvec][28]} -both
add_ignored_outputs {irqo[2][rstvec][29]} -both
add_ignored_outputs {irqo[2][rstvec][30]} -both
add_ignored_outputs {irqo[2][rstvec][31]} -both
add_ignored_outputs {irqo[3][index][0]} -both
add_ignored_outputs {irqo[3][index][1]} -both
add_ignored_outputs {irqo[3][index][2]} -both
add_ignored_outputs {irqo[3][index][3]} -both
add_ignored_outputs {irqo[3][rstvec][12]} -both
add_ignored_outputs {irqo[3][rstvec][13]} -both
add_ignored_outputs {irqo[3][rstvec][14]} -both
add_ignored_outputs {irqo[3][rstvec][15]} -both
add_ignored_outputs {irqo[3][rstvec][16]} -both
add_ignored_outputs {irqo[3][rstvec][17]} -both
add_ignored_outputs {irqo[3][rstvec][18]} -both
add_ignored_outputs {irqo[3][rstvec][19]} -both
add_ignored_outputs {irqo[3][rstvec][20]} -both
add_ignored_outputs {irqo[3][rstvec][21]} -both
add_ignored_outputs {irqo[3][rstvec][22]} -both
add_ignored_outputs {irqo[3][rstvec][23]} -both
add_ignored_outputs {irqo[3][rstvec][24]} -both
add_ignored_outputs {irqo[3][rstvec][25]} -both
add_ignored_outputs {irqo[3][rstvec][26]} -both
add_ignored_outputs {irqo[3][rstvec][27]} -both
add_ignored_outputs {irqo[3][rstvec][28]} -both
add_ignored_outputs {irqo[3][rstvec][29]} -both
add_ignored_outputs {irqo[3][rstvec][30]} -both
add_ignored_outputs {irqo[3][rstvec][31]} -both
set_system_mode lec
add_compared_points -all

// Remove pins that aren't used by the top design

compare
report_verification -compare_result
exit
