# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/imports/opencores/wb_lcd/src/lcd_defines.v
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/imports/opencores/wb_lcd/src/delay_counter.v
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/imports/opencores/wb_lcd/src/lcd_display.v
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/imports/opencores/wb_lcd/src/wb_lcd.v
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/new/top.v
}
read_vhdl -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/imports/opencores/powerSequencer/src/retrigg_timer.vhd
  /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/sources_1/imports/opencores/powerSequencer/src/PowerSequencer.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/wb_lcd_base/wb_lcd_base.srcs/constrs_1/new/top.xdc]


synth_design -top top -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
