add_ignored_outputs {ahbso[hconfig][0][0]} -both
add_ignored_outputs {ahbso[hconfig][0][10]} -both
add_ignored_outputs {ahbso[hconfig][0][11]} -both
add_ignored_outputs {ahbso[hconfig][0][16]} -both
add_ignored_outputs {ahbso[hconfig][0][17]} -both
add_ignored_outputs {ahbso[hconfig][0][18]} -both
add_ignored_outputs {ahbso[hconfig][0][19]} -both
add_ignored_outputs {ahbso[hconfig][0][1]} -both
add_ignored_outputs {ahbso[hconfig][0][20]} -both
add_ignored_outputs {ahbso[hconfig][0][21]} -both
add_ignored_outputs {ahbso[hconfig][0][22]} -both
add_ignored_outputs {ahbso[hconfig][0][23]} -both
add_ignored_outputs {ahbso[hconfig][0][24]} -both
add_ignored_outputs {ahbso[hconfig][0][25]} -both
add_ignored_outputs {ahbso[hconfig][0][27]} -both
add_ignored_outputs {ahbso[hconfig][0][28]} -both
add_ignored_outputs {ahbso[hconfig][0][29]} -both
add_ignored_outputs {ahbso[hconfig][0][2]} -both
add_ignored_outputs {ahbso[hconfig][0][30]} -both
add_ignored_outputs {ahbso[hconfig][0][31]} -both
add_ignored_outputs {ahbso[hconfig][0][3]} -both
add_ignored_outputs {ahbso[hconfig][0][4]} -both
add_ignored_outputs {ahbso[hconfig][0][6]} -both
add_ignored_outputs {ahbso[hconfig][0][7]} -both
add_ignored_outputs {ahbso[hconfig][0][8]} -both
add_ignored_outputs {ahbso[hconfig][0][9]} -both
add_ignored_outputs {ahbso[hconfig][2][0]} -both
add_ignored_outputs {ahbso[hconfig][2][10]} -both
add_ignored_outputs {ahbso[hconfig][2][11]} -both
add_ignored_outputs {ahbso[hconfig][2][12]} -both
add_ignored_outputs {ahbso[hconfig][2][13]} -both
add_ignored_outputs {ahbso[hconfig][2][14]} -both
add_ignored_outputs {ahbso[hconfig][2][15]} -both
add_ignored_outputs {ahbso[hconfig][2][16]} -both
add_ignored_outputs {ahbso[hconfig][2][17]} -both
add_ignored_outputs {ahbso[hconfig][2][18]} -both
add_ignored_outputs {ahbso[hconfig][2][19]} -both
add_ignored_outputs {ahbso[hconfig][2][1]} -both
add_ignored_outputs {ahbso[hconfig][2][20]} -both
add_ignored_outputs {ahbso[hconfig][2][21]} -both
add_ignored_outputs {ahbso[hconfig][2][22]} -both
add_ignored_outputs {ahbso[hconfig][2][23]} -both
add_ignored_outputs {ahbso[hconfig][2][24]} -both
add_ignored_outputs {ahbso[hconfig][2][25]} -both
add_ignored_outputs {ahbso[hconfig][2][26]} -both
add_ignored_outputs {ahbso[hconfig][2][27]} -both
add_ignored_outputs {ahbso[hconfig][2][28]} -both
add_ignored_outputs {ahbso[hconfig][2][29]} -both
add_ignored_outputs {ahbso[hconfig][2][2]} -both
add_ignored_outputs {ahbso[hconfig][2][30]} -both
add_ignored_outputs {ahbso[hconfig][2][31]} -both
add_ignored_outputs {ahbso[hconfig][2][3]} -both
add_ignored_outputs {ahbso[hconfig][2][4]} -both
add_ignored_outputs {ahbso[hconfig][2][5]} -both
add_ignored_outputs {ahbso[hconfig][2][6]} -both
add_ignored_outputs {ahbso[hconfig][2][7]} -both
add_ignored_outputs {ahbso[hconfig][2][8]} -both
add_ignored_outputs {ahbso[hconfig][2][9]} -both
add_ignored_outputs {ahbso[hconfig][4][12]} -both
add_ignored_outputs {ahbso[hconfig][4][18]} -both
add_ignored_outputs {ahbso[hconfig][4][19]} -both
add_ignored_outputs {ahbso[hconfig][4][20]} -both
add_ignored_outputs {ahbso[hconfig][4][21]} -both
add_ignored_outputs {ahbso[hconfig][4][22]} -both
add_ignored_outputs {ahbso[hconfig][4][23]} -both
add_ignored_outputs {ahbso[hconfig][4][24]} -both
add_ignored_outputs {ahbso[hconfig][4][25]} -both
add_ignored_outputs {ahbso[hconfig][4][26]} -both
add_ignored_outputs {ahbso[hconfig][4][27]} -both
add_ignored_outputs {ahbso[hconfig][4][28]} -both
add_ignored_outputs {ahbso[hconfig][4][2]} -both
add_ignored_outputs {ahbso[hconfig][4][30]} -both
add_ignored_outputs {ahbso[hconfig][4][31]} -both
add_ignored_outputs {ahbso[hconfig][4][3]} -both
add_ignored_outputs {ahbso[hconfig][6][18]} -both
add_ignored_outputs {ahbso[hconfig][6][19]} -both
add_ignored_outputs {ahbso[hconfig][6][20]} -both
add_ignored_outputs {ahbso[hconfig][6][21]} -both
add_ignored_outputs {ahbso[hconfig][6][22]} -both
add_ignored_outputs {ahbso[hconfig][6][23]} -both
add_ignored_outputs {ahbso[hconfig][6][24]} -both
add_ignored_outputs {ahbso[hconfig][6][25]} -both
add_ignored_outputs {ahbso[hconfig][6][26]} -both
add_ignored_outputs {ahbso[hconfig][6][27]} -both
add_ignored_outputs {ahbso[hconfig][6][28]} -both
add_ignored_outputs {ahbso[hconfig][6][29]} -both
add_ignored_outputs {ahbso[hconfig][6][2]} -both
add_ignored_outputs {ahbso[hconfig][6][3]} -both
add_ignored_outputs {ahbso[hindex][0]} -both
add_ignored_outputs {ahbso[hindex][1]} -both
add_ignored_outputs {ahbso[hindex][2]} -both
add_ignored_outputs {ahbso[hindex][3]} -both
add_ignored_outputs {ahbso[hirq][0]} -both
add_ignored_outputs {ahbso[hirq][16]} -both
add_ignored_outputs {ahbso[hirq][17]} -both
add_ignored_outputs {ahbso[hirq][18]} -both
add_ignored_outputs {ahbso[hirq][19]} -both
add_ignored_outputs {ahbso[hirq][20]} -both
add_ignored_outputs {ahbso[hirq][21]} -both
add_ignored_outputs {ahbso[hirq][22]} -both
add_ignored_outputs {ahbso[hirq][23]} -both
add_ignored_outputs {ahbso[hirq][24]} -both
add_ignored_outputs {ahbso[hirq][25]} -both
add_ignored_outputs {ahbso[hirq][26]} -both
add_ignored_outputs {ahbso[hirq][27]} -both
add_ignored_outputs {ahbso[hirq][28]} -both
add_ignored_outputs {ahbso[hirq][29]} -both
add_ignored_outputs {ahbso[hirq][30]} -both
add_ignored_outputs {ahbso[hirq][31]} -both
add_ignored_outputs {ahbso[hsplit][0]} -both
add_ignored_outputs {ahbso[hsplit][10]} -both
add_ignored_outputs {ahbso[hsplit][11]} -both
add_ignored_outputs {ahbso[hsplit][12]} -both
add_ignored_outputs {ahbso[hsplit][13]} -both
add_ignored_outputs {ahbso[hsplit][14]} -both
add_ignored_outputs {ahbso[hsplit][15]} -both
add_ignored_outputs {ahbso[hsplit][1]} -both
add_ignored_outputs {ahbso[hsplit][2]} -both
add_ignored_outputs {ahbso[hsplit][3]} -both
add_ignored_outputs {ahbso[hsplit][4]} -both
add_ignored_outputs {ahbso[hsplit][5]} -both
add_ignored_outputs {ahbso[hsplit][6]} -both
add_ignored_outputs {ahbso[hsplit][7]} -both
add_ignored_outputs {ahbso[hsplit][8]} -both
add_ignored_outputs {ahbso[hsplit][9]} -both
add_ignored_outputs {apbo[pconfig][0][12]} -both
add_ignored_outputs {apbo[pconfig][0][13]} -both
add_ignored_outputs {apbo[pconfig][0][14]} -both
add_ignored_outputs {apbo[pconfig][0][16]} -both
add_ignored_outputs {apbo[pconfig][0][20]} -both
add_ignored_outputs {apbo[pconfig][0][23]} -both
add_ignored_outputs {apbo[pconfig][0][27]} -both
add_ignored_outputs {apbo[pconfig][0][28]} -both
add_ignored_outputs {apbo[pconfig][0][29]} -both
add_ignored_outputs {apbo[pconfig][1][17]} -both
add_ignored_outputs {apbo[pconfig][1][18]} -both
add_ignored_outputs {apbo[pconfig][1][19]} -both
add_ignored_outputs {apbo[pconfig][1][22]} -both
add_ignored_outputs {apbo[pconfig][1][25]} -both
add_ignored_outputs {apbo[pconfig][1][2]} -both
add_ignored_outputs {apbo[pconfig][1][31]} -both
add_ignored_outputs {apbo[pconfig][1][3]} -both
add_ignored_outputs {apbo[pindex][0]} -both
add_ignored_outputs {apbo[pindex][1]} -both
add_ignored_outputs {apbo[pindex][2]} -both
add_ignored_outputs {apbo[pindex][3]} -both
add_ignored_outputs {apbo[pirq][0]} -both
add_ignored_outputs {apbo[pirq][10]} -both
add_ignored_outputs {apbo[pirq][11]} -both
add_ignored_outputs {apbo[pirq][12]} -both
add_ignored_outputs {apbo[pirq][13]} -both
add_ignored_outputs {apbo[pirq][14]} -both
add_ignored_outputs {apbo[pirq][15]} -both
add_ignored_outputs {apbo[pirq][16]} -both
add_ignored_outputs {apbo[pirq][17]} -both
add_ignored_outputs {apbo[pirq][18]} -both
add_ignored_outputs {apbo[pirq][19]} -both
add_ignored_outputs {apbo[pirq][1]} -both
add_ignored_outputs {apbo[pirq][20]} -both
add_ignored_outputs {apbo[pirq][21]} -both
add_ignored_outputs {apbo[pirq][22]} -both
add_ignored_outputs {apbo[pirq][23]} -both
add_ignored_outputs {apbo[pirq][24]} -both
add_ignored_outputs {apbo[pirq][25]} -both
add_ignored_outputs {apbo[pirq][26]} -both
add_ignored_outputs {apbo[pirq][27]} -both
add_ignored_outputs {apbo[pirq][28]} -both
add_ignored_outputs {apbo[pirq][29]} -both
add_ignored_outputs {apbo[pirq][2]} -both
add_ignored_outputs {apbo[pirq][30]} -both
add_ignored_outputs {apbo[pirq][31]} -both
add_ignored_outputs {apbo[pirq][3]} -both
add_ignored_outputs {apbo[pirq][4]} -both
add_ignored_outputs {apbo[pirq][5]} -both
add_ignored_outputs {apbo[pirq][6]} -both
add_ignored_outputs {apbo[pirq][7]} -both
add_ignored_outputs {apbo[pirq][8]} -both
add_ignored_outputs {apbo[pirq][9]} -both

add_ignored_outputs {memo[address][0]} -golden
add_ignored_outputs {memo[address][24]} -golden
add_ignored_outputs {memo[address][25]} -golden
add_ignored_outputs {memo[address][26]} -golden
add_ignored_outputs {memo[address][27]} -golden
add_ignored_outputs {memo[address][28]} -golden
add_ignored_outputs {memo[address][29]} -golden
add_ignored_outputs {memo[address][30]} -golden
add_ignored_outputs {memo[address][31]} -golden

add_ignored_outputs {^memo[address][0]} -revised
add_ignored_outputs {^memo[address][24]} -revised
add_ignored_outputs {^memo[address][25]} -revised
add_ignored_outputs {^memo[address][26]} -revised
add_ignored_outputs {^memo[address][27]} -revised
add_ignored_outputs {^memo[address][28]} -revised
add_ignored_outputs {^memo[address][29]} -revised
add_ignored_outputs {^memo[address][30]} -revised
add_ignored_outputs {memo} -revised

add_ignored_outputs {memo[bdrive][2]} -both
add_ignored_outputs {memo[bdrive][3]} -both
add_ignored_outputs {memo[cb][0]} -both
add_ignored_outputs {memo[cb][10]} -both
add_ignored_outputs {memo[cb][11]} -both
add_ignored_outputs {memo[cb][12]} -both
add_ignored_outputs {memo[cb][13]} -both
add_ignored_outputs {memo[cb][14]} -both
add_ignored_outputs {memo[cb][15]} -both
add_ignored_outputs {memo[cb][1]} -both
add_ignored_outputs {memo[cb][2]} -both
add_ignored_outputs {memo[cb][3]} -both
add_ignored_outputs {memo[cb][4]} -both
add_ignored_outputs {memo[cb][5]} -both
add_ignored_outputs {memo[cb][6]} -both
add_ignored_outputs {memo[cb][7]} -both
add_ignored_outputs {memo[cb][8]} -both
add_ignored_outputs {memo[cb][9]} -both
add_ignored_outputs {memo[ce]} -both
add_ignored_outputs {memo[data][0]} -both
add_ignored_outputs {memo[data][10]} -both
add_ignored_outputs {memo[data][11]} -both
add_ignored_outputs {memo[data][12]} -both
add_ignored_outputs {memo[data][13]} -both
add_ignored_outputs {memo[data][14]} -both
add_ignored_outputs {memo[data][15]} -both
add_ignored_outputs {memo[data][1]} -both
add_ignored_outputs {memo[data][2]} -both
add_ignored_outputs {memo[data][3]} -both
add_ignored_outputs {memo[data][4]} -both
add_ignored_outputs {memo[data][5]} -both
add_ignored_outputs {memo[data][6]} -both
add_ignored_outputs {memo[data][7]} -both
add_ignored_outputs {memo[data][8]} -both
add_ignored_outputs {memo[data][9]} -both
add_ignored_outputs {memo[iosn]} -both
add_ignored_outputs {memo[mben][2]} -both
add_ignored_outputs {memo[mben][3]} -both
add_ignored_outputs {memo[ramn]} -both
add_ignored_outputs {memo[ramoen][0]} -both
add_ignored_outputs {memo[ramoen][1]} -both
add_ignored_outputs {memo[ramoen][2]} -both
add_ignored_outputs {memo[ramoen][3]} -both
add_ignored_outputs {memo[ramoen][4]} -both
add_ignored_outputs {memo[ramoen][5]} -both
add_ignored_outputs {memo[ramoen][6]} -both
add_ignored_outputs {memo[ramoen][7]} -both
add_ignored_outputs {memo[ramsn][1]} -both
add_ignored_outputs {memo[ramsn][2]} -both
add_ignored_outputs {memo[ramsn][3]} -both
add_ignored_outputs {memo[ramsn][4]} -both
add_ignored_outputs {memo[ramsn][5]} -both
add_ignored_outputs {memo[ramsn][6]} -both
add_ignored_outputs {memo[ramsn][7]} -both
add_ignored_outputs {memo[read]} -both
add_ignored_outputs {memo[romn]} -both
add_ignored_outputs {memo[romsn][0]} -both
add_ignored_outputs {memo[romsn][1]} -both
add_ignored_outputs {memo[romsn][2]} -both
add_ignored_outputs {memo[romsn][3]} -both
add_ignored_outputs {memo[romsn][4]} -both
add_ignored_outputs {memo[romsn][5]} -both
add_ignored_outputs {memo[romsn][6]} -both
add_ignored_outputs {memo[romsn][7]} -both
add_ignored_outputs {memo[rs_edac_en]} -both
add_ignored_outputs {memo[sa][0]} -both
add_ignored_outputs {memo[sa][10]} -both
add_ignored_outputs {memo[sa][11]} -both
add_ignored_outputs {memo[sa][12]} -both
add_ignored_outputs {memo[sa][13]} -both
add_ignored_outputs {memo[sa][14]} -both
add_ignored_outputs {memo[sa][1]} -both
add_ignored_outputs {memo[sa][2]} -both
add_ignored_outputs {memo[sa][3]} -both
add_ignored_outputs {memo[sa][4]} -both
add_ignored_outputs {memo[sa][5]} -both
add_ignored_outputs {memo[sa][6]} -both
add_ignored_outputs {memo[sa][7]} -both
add_ignored_outputs {memo[sa][8]} -both
add_ignored_outputs {memo[sa][9]} -both
add_ignored_outputs {memo[scb][0]} -both
add_ignored_outputs {memo[scb][10]} -both
add_ignored_outputs {memo[scb][11]} -both
add_ignored_outputs {memo[scb][12]} -both
add_ignored_outputs {memo[scb][13]} -both
add_ignored_outputs {memo[scb][14]} -both
add_ignored_outputs {memo[scb][15]} -both
add_ignored_outputs {memo[scb][1]} -both
add_ignored_outputs {memo[scb][2]} -both
add_ignored_outputs {memo[scb][3]} -both
add_ignored_outputs {memo[scb][4]} -both
add_ignored_outputs {memo[scb][5]} -both
add_ignored_outputs {memo[scb][6]} -both
add_ignored_outputs {memo[scb][7]} -both
add_ignored_outputs {memo[scb][8]} -both
add_ignored_outputs {memo[scb][9]} -both
add_ignored_outputs {memo[sddata][0]} -both
add_ignored_outputs {memo[sddata][10]} -both
add_ignored_outputs {memo[sddata][11]} -both
add_ignored_outputs {memo[sddata][12]} -both
add_ignored_outputs {memo[sddata][13]} -both
add_ignored_outputs {memo[sddata][14]} -both
add_ignored_outputs {memo[sddata][15]} -both
add_ignored_outputs {memo[sddata][16]} -both
add_ignored_outputs {memo[sddata][17]} -both
add_ignored_outputs {memo[sddata][18]} -both
add_ignored_outputs {memo[sddata][19]} -both
add_ignored_outputs {memo[sddata][1]} -both
add_ignored_outputs {memo[sddata][20]} -both
add_ignored_outputs {memo[sddata][21]} -both
add_ignored_outputs {memo[sddata][22]} -both
add_ignored_outputs {memo[sddata][23]} -both
add_ignored_outputs {memo[sddata][24]} -both
add_ignored_outputs {memo[sddata][25]} -both
add_ignored_outputs {memo[sddata][26]} -both
add_ignored_outputs {memo[sddata][27]} -both
add_ignored_outputs {memo[sddata][28]} -both
add_ignored_outputs {memo[sddata][29]} -both
add_ignored_outputs {memo[sddata][2]} -both
add_ignored_outputs {memo[sddata][30]} -both
add_ignored_outputs {memo[sddata][31]} -both
add_ignored_outputs {memo[sddata][32]} -both
add_ignored_outputs {memo[sddata][33]} -both
add_ignored_outputs {memo[sddata][34]} -both
add_ignored_outputs {memo[sddata][35]} -both
add_ignored_outputs {memo[sddata][36]} -both
add_ignored_outputs {memo[sddata][37]} -both
add_ignored_outputs {memo[sddata][38]} -both
add_ignored_outputs {memo[sddata][39]} -both
add_ignored_outputs {memo[sddata][3]} -both
add_ignored_outputs {memo[sddata][40]} -both
add_ignored_outputs {memo[sddata][41]} -both
add_ignored_outputs {memo[sddata][42]} -both
add_ignored_outputs {memo[sddata][43]} -both
add_ignored_outputs {memo[sddata][44]} -both
add_ignored_outputs {memo[sddata][45]} -both
add_ignored_outputs {memo[sddata][46]} -both
add_ignored_outputs {memo[sddata][47]} -both
add_ignored_outputs {memo[sddata][48]} -both
add_ignored_outputs {memo[sddata][49]} -both
add_ignored_outputs {memo[sddata][4]} -both
add_ignored_outputs {memo[sddata][50]} -both
add_ignored_outputs {memo[sddata][51]} -both
add_ignored_outputs {memo[sddata][52]} -both
add_ignored_outputs {memo[sddata][53]} -both
add_ignored_outputs {memo[sddata][54]} -both
add_ignored_outputs {memo[sddata][55]} -both
add_ignored_outputs {memo[sddata][56]} -both
add_ignored_outputs {memo[sddata][57]} -both
add_ignored_outputs {memo[sddata][58]} -both
add_ignored_outputs {memo[sddata][59]} -both
add_ignored_outputs {memo[sddata][5]} -both
add_ignored_outputs {memo[sddata][60]} -both
add_ignored_outputs {memo[sddata][61]} -both
add_ignored_outputs {memo[sddata][62]} -both
add_ignored_outputs {memo[sddata][63]} -both
add_ignored_outputs {memo[sddata][6]} -both
add_ignored_outputs {memo[sddata][7]} -both
add_ignored_outputs {memo[sddata][8]} -both
add_ignored_outputs {memo[sddata][9]} -both
add_ignored_outputs {memo[sdram_en]} -both
add_ignored_outputs {memo[svbdrive][0]} -both
add_ignored_outputs {memo[svbdrive][10]} -both
add_ignored_outputs {memo[svbdrive][11]} -both
add_ignored_outputs {memo[svbdrive][12]} -both
add_ignored_outputs {memo[svbdrive][13]} -both
add_ignored_outputs {memo[svbdrive][14]} -both
add_ignored_outputs {memo[svbdrive][15]} -both
add_ignored_outputs {memo[svbdrive][16]} -both
add_ignored_outputs {memo[svbdrive][17]} -both
add_ignored_outputs {memo[svbdrive][18]} -both
add_ignored_outputs {memo[svbdrive][19]} -both
add_ignored_outputs {memo[svbdrive][1]} -both
add_ignored_outputs {memo[svbdrive][20]} -both
add_ignored_outputs {memo[svbdrive][21]} -both
add_ignored_outputs {memo[svbdrive][22]} -both
add_ignored_outputs {memo[svbdrive][23]} -both
add_ignored_outputs {memo[svbdrive][24]} -both
add_ignored_outputs {memo[svbdrive][25]} -both
add_ignored_outputs {memo[svbdrive][26]} -both
add_ignored_outputs {memo[svbdrive][27]} -both
add_ignored_outputs {memo[svbdrive][28]} -both
add_ignored_outputs {memo[svbdrive][29]} -both
add_ignored_outputs {memo[svbdrive][2]} -both
add_ignored_outputs {memo[svbdrive][30]} -both
add_ignored_outputs {memo[svbdrive][31]} -both
add_ignored_outputs {memo[svbdrive][32]} -both
add_ignored_outputs {memo[svbdrive][33]} -both
add_ignored_outputs {memo[svbdrive][34]} -both
add_ignored_outputs {memo[svbdrive][35]} -both
add_ignored_outputs {memo[svbdrive][36]} -both
add_ignored_outputs {memo[svbdrive][37]} -both
add_ignored_outputs {memo[svbdrive][38]} -both
add_ignored_outputs {memo[svbdrive][39]} -both
add_ignored_outputs {memo[svbdrive][3]} -both
add_ignored_outputs {memo[svbdrive][40]} -both
add_ignored_outputs {memo[svbdrive][41]} -both
add_ignored_outputs {memo[svbdrive][42]} -both
add_ignored_outputs {memo[svbdrive][43]} -both
add_ignored_outputs {memo[svbdrive][44]} -both
add_ignored_outputs {memo[svbdrive][45]} -both
add_ignored_outputs {memo[svbdrive][46]} -both
add_ignored_outputs {memo[svbdrive][47]} -both
add_ignored_outputs {memo[svbdrive][48]} -both
add_ignored_outputs {memo[svbdrive][49]} -both
add_ignored_outputs {memo[svbdrive][4]} -both
add_ignored_outputs {memo[svbdrive][50]} -both
add_ignored_outputs {memo[svbdrive][51]} -both
add_ignored_outputs {memo[svbdrive][52]} -both
add_ignored_outputs {memo[svbdrive][53]} -both
add_ignored_outputs {memo[svbdrive][54]} -both
add_ignored_outputs {memo[svbdrive][55]} -both
add_ignored_outputs {memo[svbdrive][56]} -both
add_ignored_outputs {memo[svbdrive][57]} -both
add_ignored_outputs {memo[svbdrive][58]} -both
add_ignored_outputs {memo[svbdrive][59]} -both
add_ignored_outputs {memo[svbdrive][5]} -both
add_ignored_outputs {memo[svbdrive][60]} -both
add_ignored_outputs {memo[svbdrive][61]} -both
add_ignored_outputs {memo[svbdrive][62]} -both
add_ignored_outputs {memo[svbdrive][63]} -both
add_ignored_outputs {memo[svbdrive][6]} -both
add_ignored_outputs {memo[svbdrive][7]} -both
add_ignored_outputs {memo[svbdrive][8]} -both
add_ignored_outputs {memo[svbdrive][9]} -both
add_ignored_outputs {memo[svcdrive][0]} -both
add_ignored_outputs {memo[svcdrive][10]} -both
add_ignored_outputs {memo[svcdrive][11]} -both
add_ignored_outputs {memo[svcdrive][12]} -both
add_ignored_outputs {memo[svcdrive][13]} -both
add_ignored_outputs {memo[svcdrive][14]} -both
add_ignored_outputs {memo[svcdrive][15]} -both
add_ignored_outputs {memo[svcdrive][1]} -both
add_ignored_outputs {memo[svcdrive][2]} -both
add_ignored_outputs {memo[svcdrive][3]} -both
add_ignored_outputs {memo[svcdrive][4]} -both
add_ignored_outputs {memo[svcdrive][5]} -both
add_ignored_outputs {memo[svcdrive][6]} -both
add_ignored_outputs {memo[svcdrive][7]} -both
add_ignored_outputs {memo[svcdrive][8]} -both
add_ignored_outputs {memo[svcdrive][9]} -both
add_ignored_outputs {memo[vbdrive][0]} -both
add_ignored_outputs {memo[vbdrive][10]} -both
add_ignored_outputs {memo[vbdrive][11]} -both
add_ignored_outputs {memo[vbdrive][12]} -both
add_ignored_outputs {memo[vbdrive][13]} -both
add_ignored_outputs {memo[vbdrive][14]} -both
add_ignored_outputs {memo[vbdrive][15]} -both
add_ignored_outputs {memo[vbdrive][16]} -both
add_ignored_outputs {memo[vbdrive][17]} -both
add_ignored_outputs {memo[vbdrive][18]} -both
add_ignored_outputs {memo[vbdrive][19]} -both
add_ignored_outputs {memo[vbdrive][1]} -both
add_ignored_outputs {memo[vbdrive][20]} -both
add_ignored_outputs {memo[vbdrive][21]} -both
add_ignored_outputs {memo[vbdrive][22]} -both
add_ignored_outputs {memo[vbdrive][23]} -both
add_ignored_outputs {memo[vbdrive][24]} -both
add_ignored_outputs {memo[vbdrive][25]} -both
add_ignored_outputs {memo[vbdrive][26]} -both
add_ignored_outputs {memo[vbdrive][27]} -both
add_ignored_outputs {memo[vbdrive][28]} -both
add_ignored_outputs {memo[vbdrive][29]} -both
add_ignored_outputs {memo[vbdrive][2]} -both
add_ignored_outputs {memo[vbdrive][30]} -both
add_ignored_outputs {memo[vbdrive][31]} -both
add_ignored_outputs {memo[vbdrive][3]} -both
add_ignored_outputs {memo[vbdrive][4]} -both
add_ignored_outputs {memo[vbdrive][5]} -both
add_ignored_outputs {memo[vbdrive][6]} -both
add_ignored_outputs {memo[vbdrive][7]} -both
add_ignored_outputs {memo[vbdrive][8]} -both
add_ignored_outputs {memo[vbdrive][9]} -both
add_ignored_outputs {memo[vcdrive][0]} -both
add_ignored_outputs {memo[vcdrive][10]} -both
add_ignored_outputs {memo[vcdrive][11]} -both
add_ignored_outputs {memo[vcdrive][12]} -both
add_ignored_outputs {memo[vcdrive][13]} -both
add_ignored_outputs {memo[vcdrive][14]} -both
add_ignored_outputs {memo[vcdrive][15]} -both
add_ignored_outputs {memo[vcdrive][1]} -both
add_ignored_outputs {memo[vcdrive][2]} -both
add_ignored_outputs {memo[vcdrive][3]} -both
add_ignored_outputs {memo[vcdrive][4]} -both
add_ignored_outputs {memo[vcdrive][5]} -both
add_ignored_outputs {memo[vcdrive][6]} -both
add_ignored_outputs {memo[vcdrive][7]} -both
add_ignored_outputs {memo[vcdrive][8]} -both
add_ignored_outputs {memo[vcdrive][9]} -both
add_ignored_outputs {memo[wrn][0]} -both
add_ignored_outputs {memo[wrn][1]} -both
add_ignored_outputs {memo[wrn][2]} -both
add_ignored_outputs {memo[wrn][3]} -both
add_ignored_outputs {sdo[casn]} -both
add_ignored_outputs {sdo[dqm][0]} -both
add_ignored_outputs {sdo[dqm][1]} -both
add_ignored_outputs {sdo[dqm][2]} -both
add_ignored_outputs {sdo[dqm][3]} -both
add_ignored_outputs {sdo[dqm][4]} -both
add_ignored_outputs {sdo[dqm][5]} -both
add_ignored_outputs {sdo[dqm][6]} -both
add_ignored_outputs {sdo[dqm][7]} -both
add_ignored_outputs {sdo[rasn]} -both
add_ignored_outputs {sdo[sdcke][0]} -both
add_ignored_outputs {sdo[sdcke][1]} -both
add_ignored_outputs {sdo[sdcsn][0]} -both
add_ignored_outputs {sdo[sdcsn][1]} -both
add_ignored_outputs {sdo[sdwen]} -both
set_system_mode lec
add_compared_points -all

// Remove pins that aren't used by the top design

compare
report_verification -compare_result
exit
