# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/amber_base/amber_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/amber_base/amber_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog {
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_localparams.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_functions.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/global_defines.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_config_defines.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/memory_configuration.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a23_functions.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a23_localparams.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a23_config_defines.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/register_addresses.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/system_config_defines.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/system_functions.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/global_timescale.vh
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/debug_functions.vh
}
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_shifter.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/generic_sram_line_en.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/generic_sram_byte_en.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_wishbone_buf.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_register_bank.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_multiply.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_icache.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_dcache.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_barrel_shift.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_alu.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_write_back.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_wishbone.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_mem.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_fetch.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_execute.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_decode.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/a25_coprocessor.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/amber.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/new/top.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/timescale.v
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/vivado_workspace/ooc_amber/Sources/hdl/eth_defines.v
}
read_vhdl -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/hdl/modmult.vhd
  /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/sources_1/imports/hdl/basicrsa.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/constrs_1/imports/new/constr.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/amber_base/amber_base.srcs/constrs_1/imports/new/constr.xdc]


synth_design -top top -part xc7a100tcsg324-3 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
