# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/sean/vivado_workspace/sap_dt/sap_dt.cache/wt [current_project]
set_property parent.project_path /home/sean/vivado_workspace/sap_dt/sap_dt.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/padder1_l.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/round.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/rconst2in1.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/padder1_h.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/round2in1.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/rconst.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/hdl/Simon_bit_serial_key_expansion_FPGA.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/hdl/Simon_bit_serial_datapath_FPGA.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/padder_h.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/padder_l.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/f_permutation_l.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/f_permutation_h.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/hdl/simon_core.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_random_pulse_generator/Sources/hdl/random_pulse_generator.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/ooc_sap/ooc_sap_impl.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/sha3_low_throughput.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/sha3_high_throughput.v
  /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/sources_1/imports/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/constrs_1/imports/constrs_1/imports/new/constr.xdc
set_property used_in_implementation false [get_files /home/sean/vivado_workspace/sap_dt/sap_dt.srcs/constrs_1/imports/constrs_1/imports/new/constr.xdc]


synth_design -top top -part xc7a100tcsg324-3 -flatten_hierarchy full


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
