# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/round.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/rconst.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/padder1_l.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/rconst2in1.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/padder1_h.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/round2in1.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/hdl/Simon_bit_serial_key_expansion_FPGA.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/hdl/Simon_bit_serial_datapath_FPGA.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/padder_h.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/padder_l.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/f_permutation_l.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/f_permutation_h.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/hdl/simon_core.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_random_pulse_generator/Sources/hdl/random_pulse_generator.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_low_throughput/Sources/hdl/sha3_low_throughput.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sha3_high_throughput/Sources/hdl/sha3_high_throughput.v
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/new/top.v
}
read_vhdl -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/rom_16_8_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/pc_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/o_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/mar_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/ir_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/irdec_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/control_unit_fsm.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/b_reg_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/alu_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/ac_behave.vhd
  /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/sources_1/imports/vivado_workspace/ooc_sap/Sources/hdl/sap.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/constrs_1/imports/constrs_1/imports/constrs_1/imports/new/constr.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/random_pulse_generator_base/random_pulse_generator_base.srcs/constrs_1/imports/constrs_1/imports/constrs_1/imports/new/constr.xdc]


synth_design -top top -part xc7a100tcsg324-3 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
