# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/y_quantizer.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/y_huff.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/y_dct.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cr_quantizer.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cr_huff.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cr_dct.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cb_quantizer.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cb_huff.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cb_dct.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/yd_q_h.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/rgb2ycbcr.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/crd_q_h.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/cbd_q_h.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/sync_fifo_ff.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/sync_fifo_32.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/pre_fifo.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/fifo_out.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/ff_checker.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/imports/hdl/jpegencode.v
  /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/constrs_1/imports/opencores/top.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/jpegencode_base/jpegencode_base.srcs/constrs_1/imports/opencores/top.xdc]


synth_design -top top -part xc7a100tcsg324-3 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
