add_ignored_outputs {b[0]} -both
add_ignored_outputs {b[1]} -both
add_ignored_outputs {b[2]} -both
add_ignored_outputs {b[3]} -both
add_ignored_outputs {b[4]} -both
add_ignored_outputs {b[5]} -both
add_ignored_outputs {b[6]} -both
add_ignored_outputs {b[7]} -both
add_ignored_outputs {busy} -both
add_ignored_outputs {c_sync} -both
add_ignored_outputs {error} -both
add_ignored_outputs {g[0]} -both
add_ignored_outputs {g[1]} -both
add_ignored_outputs {g[2]} -both
add_ignored_outputs {g[3]} -both
add_ignored_outputs {g[4]} -both
add_ignored_outputs {g[5]} -both
add_ignored_outputs {g[6]} -both
add_ignored_outputs {g[7]} -both
add_ignored_outputs {h_sync} -both
add_ignored_outputs {mem_req_rd_addr[0]} -both
add_ignored_outputs {mem_req_rd_addr[10]} -both
add_ignored_outputs {mem_req_rd_addr[11]} -both
add_ignored_outputs {mem_req_rd_addr[12]} -both
add_ignored_outputs {mem_req_rd_addr[13]} -both
add_ignored_outputs {mem_req_rd_addr[14]} -both
add_ignored_outputs {mem_req_rd_addr[15]} -both
add_ignored_outputs {mem_req_rd_addr[16]} -both
add_ignored_outputs {mem_req_rd_addr[17]} -both
add_ignored_outputs {mem_req_rd_addr[18]} -both
add_ignored_outputs {mem_req_rd_addr[19]} -both
add_ignored_outputs {mem_req_rd_addr[1]} -both
add_ignored_outputs {mem_req_rd_addr[20]} -both
add_ignored_outputs {mem_req_rd_addr[21]} -both
add_ignored_outputs {mem_req_rd_addr[2]} -both
add_ignored_outputs {mem_req_rd_addr[3]} -both
add_ignored_outputs {mem_req_rd_addr[4]} -both
add_ignored_outputs {mem_req_rd_addr[5]} -both
add_ignored_outputs {mem_req_rd_addr[6]} -both
add_ignored_outputs {mem_req_rd_addr[7]} -both
add_ignored_outputs {mem_req_rd_addr[8]} -both
add_ignored_outputs {mem_req_rd_addr[9]} -both
add_ignored_outputs {mem_req_rd_cmd[0]} -both
add_ignored_outputs {mem_req_rd_cmd[1]} -both
add_ignored_outputs {mem_res_wr_almost_full} -both
add_ignored_outputs {pixel_en} -both
add_ignored_outputs {r[0]} -both
add_ignored_outputs {r[1]} -both
add_ignored_outputs {r[2]} -both
add_ignored_outputs {r[3]} -both
add_ignored_outputs {r[4]} -both
add_ignored_outputs {r[5]} -both
add_ignored_outputs {r[6]} -both
add_ignored_outputs {r[7]} -both
add_ignored_outputs {reg_dta_out[16]} -both
add_ignored_outputs {reg_dta_out[17]} -both
add_ignored_outputs {reg_dta_out[18]} -both
add_ignored_outputs {reg_dta_out[19]} -both
add_ignored_outputs {reg_dta_out[20]} -both
add_ignored_outputs {reg_dta_out[21]} -both
add_ignored_outputs {reg_dta_out[22]} -both
add_ignored_outputs {reg_dta_out[23]} -both
add_ignored_outputs {reg_dta_out[24]} -both
add_ignored_outputs {reg_dta_out[25]} -both
add_ignored_outputs {reg_dta_out[26]} -both
add_ignored_outputs {reg_dta_out[27]} -both
add_ignored_outputs {reg_dta_out[28]} -both
add_ignored_outputs {reg_dta_out[29]} -both
add_ignored_outputs {reg_dta_out[30]} -both
add_ignored_outputs {reg_dta_out[31]} -both
add_ignored_outputs {testpoint[0]} -both
add_ignored_outputs {testpoint[10]} -both
add_ignored_outputs {testpoint[11]} -both
add_ignored_outputs {testpoint[12]} -both
add_ignored_outputs {testpoint[13]} -both
add_ignored_outputs {testpoint[14]} -both
add_ignored_outputs {testpoint[15]} -both
add_ignored_outputs {testpoint[16]} -both
add_ignored_outputs {testpoint[17]} -both
add_ignored_outputs {testpoint[18]} -both
add_ignored_outputs {testpoint[19]} -both
add_ignored_outputs {testpoint[1]} -both
add_ignored_outputs {testpoint[20]} -both
add_ignored_outputs {testpoint[21]} -both
add_ignored_outputs {testpoint[22]} -both
add_ignored_outputs {testpoint[23]} -both
add_ignored_outputs {testpoint[24]} -both
add_ignored_outputs {testpoint[25]} -both
add_ignored_outputs {testpoint[26]} -both
add_ignored_outputs {testpoint[27]} -both
add_ignored_outputs {testpoint[28]} -both
add_ignored_outputs {testpoint[29]} -both
add_ignored_outputs {testpoint[2]} -both
add_ignored_outputs {testpoint[30]} -both
add_ignored_outputs {testpoint[31]} -both
add_ignored_outputs {testpoint[32]} -both
add_ignored_outputs {testpoint[33]} -both
add_ignored_outputs {testpoint[3]} -both
add_ignored_outputs {testpoint[4]} -both
add_ignored_outputs {testpoint[5]} -both
add_ignored_outputs {testpoint[6]} -both
add_ignored_outputs {testpoint[7]} -both
add_ignored_outputs {testpoint[8]} -both
add_ignored_outputs {testpoint[9]} -both
add_ignored_outputs {u[0]} -both
add_ignored_outputs {u[1]} -both
add_ignored_outputs {u[2]} -both
add_ignored_outputs {u[3]} -both
add_ignored_outputs {u[4]} -both
add_ignored_outputs {u[5]} -both
add_ignored_outputs {u[6]} -both
add_ignored_outputs {u[7]} -both
add_ignored_outputs {v[0]} -both
add_ignored_outputs {v[1]} -both
add_ignored_outputs {v[2]} -both
add_ignored_outputs {v[3]} -both
add_ignored_outputs {v[4]} -both
add_ignored_outputs {v[5]} -both
add_ignored_outputs {v[6]} -both
add_ignored_outputs {v[7]} -both
add_ignored_outputs {v_sync} -both
add_ignored_outputs {watchdog_rst} -both
add_ignored_outputs {y[0]} -both
add_ignored_outputs {y[1]} -both
add_ignored_outputs {y[2]} -both
add_ignored_outputs {y[3]} -both
add_ignored_outputs {y[4]} -both
add_ignored_outputs {y[5]} -both
add_ignored_outputs {y[6]} -both
add_ignored_outputs {y[7]} -both
set_system_mode lec
add_compared_points -all

// Remove pins that aren't used by the top design

compare
report_verification -compare_result
exit
