add ignored outputs b[0] -both
add ignored outputs b[1] -both
add ignored outputs b[2] -both
add ignored outputs b[3] -both
add ignored outputs b[4] -both
add ignored outputs b[5] -both
add ignored outputs b[6] -both
add ignored outputs b[7] -both
add ignored outputs busy -both
add ignored outputs c_sync -both
add ignored outputs error -both
add ignored outputs g[0] -both
add ignored outputs g[1] -both
add ignored outputs g[2] -both
add ignored outputs g[3] -both
add ignored outputs g[4] -both
add ignored outputs g[5] -both
add ignored outputs g[6] -both
add ignored outputs g[7] -both
add ignored outputs h_sync -both
add ignored outputs mem_req_rd_addr[0] -both
add ignored outputs mem_req_rd_addr[10] -both
add ignored outputs mem_req_rd_addr[11] -both
add ignored outputs mem_req_rd_addr[12] -both
add ignored outputs mem_req_rd_addr[13] -both
add ignored outputs mem_req_rd_addr[14] -both
add ignored outputs mem_req_rd_addr[15] -both
add ignored outputs mem_req_rd_addr[16] -both
add ignored outputs mem_req_rd_addr[17] -both
add ignored outputs mem_req_rd_addr[18] -both
add ignored outputs mem_req_rd_addr[19] -both
add ignored outputs mem_req_rd_addr[1] -both
add ignored outputs mem_req_rd_addr[20] -both
add ignored outputs mem_req_rd_addr[21] -both
add ignored outputs mem_req_rd_addr[2] -both
add ignored outputs mem_req_rd_addr[3] -both
add ignored outputs mem_req_rd_addr[4] -both
add ignored outputs mem_req_rd_addr[5] -both
add ignored outputs mem_req_rd_addr[6] -both
add ignored outputs mem_req_rd_addr[7] -both
add ignored outputs mem_req_rd_addr[8] -both
add ignored outputs mem_req_rd_addr[9] -both
add ignored outputs mem_req_rd_cmd[0] -both
add ignored outputs mem_req_rd_cmd[1] -both
add ignored outputs mem_res_wr_almost_full -both
add ignored outputs pixel_en -both
add ignored outputs r[0] -both
add ignored outputs r[1] -both
add ignored outputs r[2] -both
add ignored outputs r[3] -both
add ignored outputs r[4] -both
add ignored outputs r[5] -both
add ignored outputs r[6] -both
add ignored outputs r[7] -both
add ignored outputs reg_dta_out[16] -both
add ignored outputs reg_dta_out[17] -both
add ignored outputs reg_dta_out[18] -both
add ignored outputs reg_dta_out[19] -both
add ignored outputs reg_dta_out[20] -both
add ignored outputs reg_dta_out[21] -both
add ignored outputs reg_dta_out[22] -both
add ignored outputs reg_dta_out[23] -both
add ignored outputs reg_dta_out[24] -both
add ignored outputs reg_dta_out[25] -both
add ignored outputs reg_dta_out[26] -both
add ignored outputs reg_dta_out[27] -both
add ignored outputs reg_dta_out[28] -both
add ignored outputs reg_dta_out[29] -both
add ignored outputs reg_dta_out[30] -both
add ignored outputs reg_dta_out[31] -both
add ignored outputs testpoint[0] -both
add ignored outputs testpoint[10] -both
add ignored outputs testpoint[11] -both
add ignored outputs testpoint[12] -both
add ignored outputs testpoint[13] -both
add ignored outputs testpoint[14] -both
add ignored outputs testpoint[15] -both
add ignored outputs testpoint[16] -both
add ignored outputs testpoint[17] -both
add ignored outputs testpoint[18] -both
add ignored outputs testpoint[19] -both
add ignored outputs testpoint[1] -both
add ignored outputs testpoint[20] -both
add ignored outputs testpoint[21] -both
add ignored outputs testpoint[22] -both
add ignored outputs testpoint[23] -both
add ignored outputs testpoint[24] -both
add ignored outputs testpoint[25] -both
add ignored outputs testpoint[26] -both
add ignored outputs testpoint[27] -both
add ignored outputs testpoint[28] -both
add ignored outputs testpoint[29] -both
add ignored outputs testpoint[2] -both
add ignored outputs testpoint[30] -both
add ignored outputs testpoint[31] -both
add ignored outputs testpoint[32] -both
add ignored outputs testpoint[33] -both
add ignored outputs testpoint[3] -both
add ignored outputs testpoint[4] -both
add ignored outputs testpoint[5] -both
add ignored outputs testpoint[6] -both
add ignored outputs testpoint[7] -both
add ignored outputs testpoint[8] -both
add ignored outputs testpoint[9] -both
add ignored outputs u[0] -both
add ignored outputs u[1] -both
add ignored outputs u[2] -both
add ignored outputs u[3] -both
add ignored outputs u[4] -both
add ignored outputs u[5] -both
add ignored outputs u[6] -both
add ignored outputs u[7] -both
add ignored outputs v[0] -both
add ignored outputs v[1] -both
add ignored outputs v[2] -both
add ignored outputs v[3] -both
add ignored outputs v[4] -both
add ignored outputs v[5] -both
add ignored outputs v[6] -both
add ignored outputs v[7] -both
add ignored outputs v_sync -both
add ignored outputs watchdog_rst -both
add ignored outputs y[0] -both
add ignored outputs y[1] -both
add ignored outputs y[2] -both
add ignored outputs y[3] -both
add ignored outputs y[4] -both
add ignored outputs y[5] -both
add ignored outputs y[6] -both
add ignored outputs y[7] -both
set system mode lec
add compared points -all

// Remove pins that aren't used by the top design

compare
report verification -compare_result
