# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/aes128_base/aes128_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/aes128_base/aes128_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/tbu.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/mem_8x1024.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/mem_1x1024.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc111.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc110.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc101.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc100.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc011.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc010.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc001.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/bmc000.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/ACS.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/aes128/src/table.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/encoder.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/decoder.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/aes128/src/round.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/viterbi_tx_rx/src/viterbi_tx_rx.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/imports/opencores/aes128/src/aes128.v
  /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/constrs_1/imports/opencores/top.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/aes128_base/aes128_base.srcs/constrs_1/imports/opencores/top.xdc]


synth_design -top top -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
