# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.cache/wt [current_project]
set_property parent.project_path /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/src/fm_3d_define.v
set_property file_type "Verilog Header" [get_files /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/src/fm_3d_define.v]
read_verilog -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_norm.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_frcp_rom.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_frcp.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_fmul.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_fadd.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_f22_to_i.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_fcnv.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_ras_state.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_ras_mem.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_ras_line.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_geo_viewport.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_geo_tri.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_geo_persdiv.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_geo_matrix.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_geo_cull.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_geo_clip.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_divider11.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/src/fm_geo_mem.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_sys.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_mem_arb.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_edgetrace.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_edgedivops.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_meshgen.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_pixout.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_pixin.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_ctlif.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_reorder.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_decay.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_scantrace.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_scandivops.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_perfcounters.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_addresses.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_edgediv.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_scandiv.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_burst.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu_filter.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/src/fm_ras.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/src/fm_geo.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/fm_3d_core/src/fm_3d_core.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/tmu/src/tmu.v
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/new/top.v
}
read_vhdl -library xil_defaultlib {
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_types.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_constants.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_utilities.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_csr.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_alu_control_unit.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_imm_decoder.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_csr_alu.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_counter.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_control_unit.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_comparator.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_alu_mux.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_alu.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_writeback.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_register_file.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_memory.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_fetch.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_execute.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_decode.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_csr_unit.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_wb_arbiter.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_wb_adapter.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_icache.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_core.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/vga80x40/src/losr.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/vga80x40/src/ctrm.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/vga80x40/src/vga80x40.vhd
  /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/sources_1/imports/opencores/pp_potato/src/pp_potato.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files /home/jgoeders/ipassurance/base/fm_3d_core_base/fm_3d_core_base.srcs/constrs_1/new/top.xdc]


synth_design -top top -part xc7a100tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
